# 1 "C:\\KG\\LESSA\\Symbian\\data\\LESSA.rss"
/*
============================================================================
 Name        : LESSA.rss
 Author      : 
 Version     :
 Copyright   : Your copyright notice
 Description : This file contains all the resources for the LESSA.
============================================================================
*/

//  RESOURCE IDENTIFIER
NAME    AWIZ // 4 letter ID

//  INCLUDES

# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikon.rh" 1
# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikon.hrh" 1



# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\uikon.hrh" 1



# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikcolor.hrh" 1
// EIKCOLOR.HRH
//
// Copyright (c) Symbian Software Ltd 1997 - 2004. All rights reserved.
//

/** RGB colour constant: black.
@publishedAll 
@released 
*/


/** RGB colour constant: dark gray.
@publishedAll 
@released 
*/


/** RGB colour constant: dark red.
@publishedAll 
@released 
*/


/** RGB colour constant: dark green.
@publishedAll 
@released 
*/


/** RGB colour constant: dark yellow.
@publishedAll 
@released 
*/


/** RGB colour constant: dark blue.
@publishedAll 
@released 
*/


/** RGB colour constant: dark magenta.
@publishedAll 
@released 
*/


/** RGB colour constant: dark cyan.
@publishedAll 
@released 
*/


/** RGB colour constant: red.
@publishedAll 
@released 
*/


/** RGB colour constant: green.
@publishedAll 
@released 
*/


/** RGB colour constant: yellow.
@publishedAll 
@released 
*/


/** RGB colour constant: blue.
@publishedAll 
@released 
*/


/** RGB colour constant: magenta.
@publishedAll 
@released 
*/


/** RGB colour constant: cyan.
@publishedAll 
@released 
*/


/** RGB colour constant: gray.
@publishedAll 
@released 
*/


/** RGB colour constant: dithered light gray.
@publishedAll 
@released 
*/


/** RGB colour constant: 1-in-4 dithered gray.
@publishedAll 
@released 
*/


/** RGB colour constant: white.
@publishedAll 
@released 
*/



/** RGB colour constant: Symbian green.
@publishedAll 
@released 
*/


/** RGB colour constant: Symbian light green.
@publishedAll 
@released 
*/


/** RGB colour constant: Symbian blue.
@publishedAll 
@released 
*/


/** RGB colour constant: Symbian dark blue.
@publishedAll 
@released 
*/


/** RGB colour constant: Symbian orange.
@publishedAll 
@released 
*/



/** Logical colour value for use in resources: The colour of a window's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in a window. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the background contents of a control. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text inside a control. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The background colour of a control's border. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in a control's border. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a control's background when highlighted for selection. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text in a control when highlighted for selection. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a control's background when dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text in a control when dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a control's background when dimmed and highlighted for selection. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text in a control when dimmed and highlighted for selection. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a dialog's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text inside a dialog. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: A dialog title's background colour. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: A dialog title's background colour when pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The text colour in a dialog's title. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The text colour in a dialog's title when pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the menubar's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in the menubar. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the menubar title's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in the menubar title. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the menupane's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in the menu pane. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the menu pane background when highlighted for selection. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in the menu pane when highlighted for selection. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the menu pane background when dimmed and highlighted. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in the menu pane when dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of text in the menu pane when dimmed and highlighted for selection. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the button background, when the button is in the unset state. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the button background when the button is in the set state. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the button background when the button is in the set state and is pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the button background when the button is in the unset state and is pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the button text. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the button text when the button is pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the button text when the button is dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the message window foreground. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the message window background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the scroll bar border. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the scroll bar shaft background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the scroll bar shaft background when dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the scroll bar shaft background when pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the background for scroll bars with no thumb and no shaft. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of scroll bar buttons. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of scroll bar buttons when pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of scroll bar buttons when dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a scroll bar thumb's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a scroll bar thumb's background when pressed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a scroll bar thumb's background when dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a scroll bar thumb's edge. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a toolbar's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text in a toolbar. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of a status pane's background. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text in a status pane. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text in a label. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of emphasised text in a label. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the text in a label when dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the label background when highlighted and dimmed. 
@publishedAll 
@released 
*/


/** Logical colour value for use in resources: The colour of the label background when highlighted. 
@publishedAll 
@released 
*/

# 4 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\uikon.hrh" 2



// EIKBTGPC.HRH







// EIKBUTB.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//




// EIKCHLST.HRH

// EIKEDWIN.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

// Introduced in avkon temporarily and deprecated:


// CEikEdwin Flags ('flags' in EDWIN resource)





























// AVKON EDWIN CONSTANTS

// Number input mode keymappings for * and # keys ('numeric_keymap' in EDWIN resource)
// If only the number mode is permitted in an editor, special characters can be
// entered by pressing # key or multitapping '*' key.
// If also text input mode is available in the editor, special characters entered
// with '*' key are shown inside special character table pop-up.
// - Default keymapping for editors that allows both number and 
// text input modes: EAknEditorAlphanumericNumberModeKeymap.
// - Default keymapping for editors that allows only number input 
// mode: EAknEditorStandardNumberModeKeymap.
//
// EAknEditorAlphanumericNumberModeKeymap value is not valid for 
// number input mode only editors. Use avkon_flags 
// EAknEditorFlagUseSCTNumericCharmap flag instead.
enum TAknEditorNumericKeymap
    {
                                            // Available characters:
    EAknEditorStandardNumberModeKeymap,     // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, *, +, p, w, #
    EAknEditorPlainNumberModeKeymap,        // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0
    EAknEditorCalculatorNumberModeKeymap,   // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, +, –, *, /, <decimal separator>
    EAknEditorConverterNumberModeKeymap,    // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, +, –, E, <decimal separator>
    EAknEditorToFieldNumberModeKeymap,      // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, +, ;
    EAknEditorFixedDiallingNumberModeKeymap,// 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, *, +, p, w, ?, #
    EAknEditorSATNumberModeKeymap,          // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, *, +, #
    EAknEditorSATHiddenNumberModeKeymap,    // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, *, #
    EAknEditorAlphanumericNumberModeKeymap, // 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, #, <all alpha mode special characters>
    EAknEditorReservedInternalUseKeymap = 100   // do not use - for internal use only 
    };

// Case mode flags for input languages that supports case.
// 'default_case' and 'allowed_case_modes' in EDWIN resource.





// Input mode flags for editors.
// 'default_input_mode' and 'allowed_input_modes' in EDWIN resource.

// All text input modes that are available in current language.



// Japanese input modes - only effective in Japanese variant.
// half-width Katakana
// full-width latin alphabet
// full-width numeric (0-9)
// full-width Katakana
// Hiragana/Kanji
// only Hiragana
// half-width Latin alphabet



// Following two are deprecated


//

// Avkon editor flags ('avkon_flags' in EDWIN resource).
// -----------------------------------------------------

// case changes are not allowed
// predictive text entry is not allowed
// editor indicators are not shown
// the cursor cannot be moved
// edit menu cannot be opened from edit key

// The character next to the cursor (if exists) is replaced by a new entered character.
// This flag has effect only in latin multitap input.

// The number input mode uses same special character table character set
// as alpha input mode if the flag is set. The flag overrides
// number mode keymapping if they are in conflict. This flag can be used
// also with number input mode only editors.

// Input language is changed to English locally in the editor.

// Chinese find mode input.

// Line feed character is added with scroll down key event 
// if the cursor is at the end of the buffer. The functionality is 
// available only in certain variants.


// NOTICE! Flag value 0x80000000 is reserved for internal use by FEP.

// EIKLABEL.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//











enum EEikLabelStandardFont
    {
    EEikLabelFontNormal,
    EEikLabelFontLegend,
    EEikLabelFontAnnotation
    };
    
// EIKLBBUT.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//





// EIKLBX.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//









// EIKMENU.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//










// more flags to determine the type of scroll bar to be used
// deprecated in Uikon 1.2



// remaining flags only used internally





//The following value is reserved       0x020000
//(Added by GT)

// EIKTBAR.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

// Toolbar flags






// Toolbar control flags




// standard toolbat sizes













// EIKCMBUT.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//





















//to be removed ...  (Comment added by GT)





// EIKLBBUT.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//




// EIKDEF.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//















// cp1252=133
// cp1252=145
// cp1252=146
// cp1252=147
// cp1252=148


enum TEikAppResourceFileStandardOffset
    {
    ESignatureResourceOffset=1,
    EDefaultNameResourceOffset,
    EAppInfoResourceOffset
    };

// Added by Bill
// Built-in app UIDs





































// EIKCMDS.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//






































































// EIKCTRLS.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

enum TEikStockControls
    {
    EEikCtCommandButton,
    EEikCtLabeledButton,
    EEikCtEdwin,
    EEikCtRichTextEditor,
    EEikCtSecretEd,
    EEikCtCheckBox,
    EEikCtChoiceList,
    EEikCtOptionButton,
    EEikCtHorOptionButList,
    EEikCtFileNameSel,
    EEikCtFileNameEd,
    EEikCtFolderNameSel,
    EEikCtFolderNameEd,
    EEikCtDriveNameSel,
    EEikCtListBox,
    EEikCtCharMap,
    EEikCtCharEd,
    EEikCtImage,
    EEikCtImageArray,
    EEikCtLabel,
    EEikCtComboBox,
    EEikCtProgInfo,
    EEikCtFlPtEd,
    EEikCtFxPtEd,
    EEikCtTwipsEd,
    EEikCtNumberEditor,
    EEikCtRangeEditor,
    EEikCtTimeEditor,
    EEikCtDateEditor,
    EEikCtTimeAndDateEditor,
    EEikCtDurationEditor,
    EEikCtTimeOffsetEditor,
    EEikCtLatitudeEditor_Not_Supported,
    EEikCtLongitudeEditor_Not_Supported,
    EEikCtBorderPreview,
    EEikCtFontPreview,
    EEikCtGraySelector,
    EEikCtWorldSelector,
    EEikCtGlobalTextEditor,
    EEikCtSoundSelector,
    EEikCtClock,
    EEikCtPrintPreview,
    EEikCtMenuButton,
    EEikCtDirContentsListBox,
    EAknCtIpFieldEditor,
    EEikCtCalendar,
    EEikCtSpacer,
    EEikCtColListBox,
    EEikCtRangeRefEditor,
    EEikCtTextButton,
    EEikCtBitmapButton,
    EEikCtDialogToolBar,
    EEikCtFileBrowser,
    EEikCtFileNameLabel,
    EEikCtUnifiedFileSel,
    EEikCtTelephoneNumberEditor,
    EEikCtTwoPictureCommandButton,
    EEikCtInverterCommandButton,
    EEikCtScrollBar,
    EEikCtArrowHeadScrollBar
    };

// not available before Release 6.1
enum TEikStockButtonGroupControls
    {
    EEikBgToolBar,
    EEikBgButtonPanel,
    EEikBgCba
    };

// EIKPRIV.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//












// > EEikBidDeferValidateFocusControl


































































//preview dialog







// setup menubutton






//printer setup






//serial port setup











//printrange setup







//print progress
                                     



//previewrange setup




//page setup














































































































// EIKDIALG.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
 
















// eikdialg.cpp seems to define 0x10000, 0x20000, 0x40000

// eikdialg.cpp seems to define 0x100000





// EEikDlgItemSeparatorAfter has been deprecated.




























// AKNLAF
// (Added by GT)

// default





// EIKSPANE.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

// Status pane server, pane declaration flags




// Status pane server, top level layout flags










// Status pane server, pane layout flags



// Status pane app constants



// Redefine the base-defined keys to Series 60 specific names.
// These key events are reserved for Series 60 Platform.









// Voice key












// Following key event are reserved for internal use by Series 60 Platform:
// EKeyF19, EKeyF20, EKeyF21, EKeyF22, EKeyF23, EKeyF24,
// EKeyApplication9, EKeyApplicationA, EKeyApplicationB, EKeyApplicationC
// EKeyApplicationD, EKeyApplicationE, EKeyApplicationF

// Scancodes (TStdScanCode) 0xE0 - 0xF7 and key codes (TKeyCode) 0xF880 - 0xF897 
// are reserved for product specific use. The meaning of the event can vary 
// in different products.

// Series 60 platform reserves all EKeyDeviceX and EKeyApplicationX events for
// future use.







# 4 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikon.hrh" 2



# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\lafpublc.hrh" 1
// LAFPUBLC.HRH
//
// Copyright (c) 2000 Symbian Ltd.  All rights reserved.
//




enum TLafReferenceButtonGroupControls
	{
	ELafBgCba=100
	};


# 7 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikon.hrh" 2



// EIKCFDLG.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
 












// EIKDIAL.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//





enum
	{
	EDialDlgButFreeDial=1,
	EDialDlgButDial,
	EDialDlgButDialOut,
	EFreeDialDlgButClear,
	EFreeDialDlgButRedial,
	EDialDlgEdwin1,
	EDialDlgEdwin2,
	EDialDlgEdwin3,
	EDialDlgEdwin4,
	EDialDlgEdwin5,
	EFreeDialDlgEdwin
	};

// EIKFBROW.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#define EEikFileBrowseHideRom				0x0001
//#define EEikFileBrowseShowSystem			0x0020
//#define EEikFileBrowseShowHidden			0x0040
//#define EEikFileBrowseAllowFolderCreation	0x0200

// EIKTIME.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//




/*
#define KEikTimeCityCountryNameWidth	15

#define EEikTimeCidSetCityCity			0x1901
#define EEikTimeCidSetCityCountry		0x1902
#define EEikTimeCidSetTimeTime			0x1911
#define EEikTimeCidSetTimeDate			0x1912
#define EEikTimeCidDstHome				0x1971
#define EEikTimeCidDstEuropean			0x1972
#define EEikTimeCidDstNorthern			0x1973
#define EEikTimeCidDstSouthern			0x1974
#define EEikTimeCidTimeFormat			0x1802
#define EEikTimeCidTimeSeparator		0x1803
#define EEikTimeCidDateFormat			0x1813
#define EEikTimeCidDateSeparator		0x1814
#define EEikTimeCidWorkayMonday			0x1770
#define EEikTimeCidWorkayTuesday		0x1771
#define EEikTimeCidWorkayWednesday		0x1772
#define EEikTimeCidWorkayThursday		0x1773
#define EEikTimeCidWorkayFriday			0x1774
#define EEikTimeCidWorkaySaturday		0x1775
#define EEikTimeCidWorkaySunday			0x1776
#define EEikTimeCidDialogDescription	0x1961
*/

// EIKCHLST.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
/*
#define EEikChlistArrayOwnedExternally	0x01
#define EEikChlistIncrementalMatching	0x02
#define EEikChlistNoPopout				0x04
*/
// EIKCAL.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
/*
#define EEikCalendarFlagStartMonthIsAlwaysJanuary	0x01
#define EEikCalendarFlagNavigateChronologically		0x02
*/
// EIKCLOCK.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
/* by H.Domon,K3 19 Apr 2001
enum
	{
	EEikLocaleConformantClockTypeChangesFormatAccordingToLocale,
	EEikLocaleConformantClockTypeDigital,
	EEikLocaleConformantClockTypeAnalog,
	EEikUsesDefaultSystemColors = 0x04
	};

enum
	{
	EEikResourceConstructedClockDigitalDisplayHorizontalTextAlignmentLeft,
	EEikResourceConstructedClockDigitalDisplayHorizontalTextAlignmentCenter,
	EEikResourceConstructedClockDigitalDisplayHorizontalTextAlignmentRight
	};

enum
	{
	EEikResourceConstructedClockDigitalDisplayVerticalTextAlignmentTop,
	EEikResourceConstructedClockDigitalDisplayVerticalTextAlignmentCenterInclDescent,
	EEikResourceConstructedClockDigitalDisplayVerticalTextAlignmentCenterExclDescent,
	EEikResourceConstructedClockDigitalDisplayVerticalTextAlignmentBottomInclDescent,
	EEikResourceConstructedClockDigitalDisplayVerticalTextAlignmentBottomExclDescent
	};

enum
	{
	EEikResourceConstructedClockAnalogDisplayHandOneRevPer12Hours,
	EEikResourceConstructedClockAnalogDisplayHandOneRevPerHour,
	EEikResourceConstructedClockAnalogDisplayHandOneRevPerMinute
	};

enum
	{
	EEikResourceConstructedClockAnalogDisplayHandFeatureLine,
	EEikResourceConstructedClockAnalogDisplayHandFeaturePolyLine,
	EEikResourceConstructedClockAnalogDisplayHandFeatureCircle
	};
by H.Domon,K3 19 Apr 2001
*/
// EIKGYSEL.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
/*
#define EEikGraySelIncrementalMatching		0x0001
#define EEikGraySelDisplay4Gray				0x0002
#define EEikGraySelDisplay16Gray			0x0004
#define EEikGraySelDisplayNoText			0x0010
#define EEikGraySelDisplay16Color			0x0020
#define EEikGraySelColorIfAvailable			0x1000
*/
// EIKMFNE.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//




//


// default is that the direction is a suffix
//
// The values of the following must be reflected in CTimeEditor in eikmfne.cpp
//







// EIKPROGI.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//


enum TEikProgressTextType
	{
	EEikProgressTextNone,
	EEikProgressTextPercentage,
	EEikProgressTextFraction
	};

// EIKRTED.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//






// EIKSPACE.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//









/*
// EIKWSEL.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

#define EEikWorldSelNoBorder				0x0001
#define EEikWorldSelSecondSelector			0x0008
#define EEikWorldSelCountrySelector			0x1000
*/

// EIKCFDLG.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
/* 
#define EEikCidFileNameSel			10
#define EEikCidFileNameEd			20 
#define EEikCidFolderNameSel		30
#define EEikCidFolderNameEd			40
#define EEikCidDriveNameSel			50

#define EEikCidUseNewFileChbx		100

#define EEikBidCreateFile			150

#define EEikBidBrowse				200
*/
// EIKFBROW.HRH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//
/*
#define EEikFileBrowseHideRom				0x0001
#define EEikFileBrowseShowSystem			0x0020
#define EEikFileBrowseShowHidden			0x0040
#define EEikFileBrowseAllowFolderCreation	0x0200
*/


enum
	{
	EEikCidImageType=1
	};

// Used to inform current foreground window group of popup windows that require it
// to fade.
enum
	{
	EEikPopupOnTop = 1100,
	EEikPopupGone
	};

// Used to tell SysAp that keylock is enabled or disabled
enum
	{
	EEikKeyLockEnabled = 1110,
	EEikKeyLockDisabled = 1111,
    EEikLeyLockDisabled = 1111,  // TODO: This should be removed!!!
	EEikKeyLockPowerKeyPressed
	};

//
// EIKHFDLG
//
// Constants used in resource for heap fail dialog
//

enum
	{
	EEikHeapFailSettingListId = 999
	};


# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikon.rh" 2



# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\uikon.rh" 1




# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\BADEF.RH" 1
// BADEF.RH
//
// Copyright (c) 1997-2000 Symbian Ltd.  All rights reserved.
//




STRUCT BA_RSS_SIGNATURE
    {
    LONG signature=0; // this value must be changed if the resource file is loaded by an environment
    SRLINK self;
    }

STRUCT TBUF
    {
    BUF buf; // non-zero terminated text string
    }

STRUCT LBUF
    {
    LTEXT txt; // leading-byte counted text string
    }

STRUCT ARRAY
    {
    STRUCT items[];
    }

STRUCT UID_NAME_PAIR
	{
	LONG uid;
	STRUCT name; // an LBUF
	}



# 5 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\uikon.rh" 2








# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\BAERRRSVR.RH" 1
// BAERRRSVR.RH
//
// Copyright (c) 2003 Symbian Ltd.  All rights reserved.
//





// Error Resolver

STRUCT ERROR_SET
	{
	STRUCT errorarrays[];
	}

STRUCT ERROR_ARRAY
	{
	LONG startError;
	LLINK errors;
	}

STRUCT SINGLE_ERROR
	{
	BYTE flags=0;
	LLINK text=0;
	}


# 13 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\uikon.rh" 2




STRUCT RESOURCE_LINK
	{
	LLINK id;
	}

STRUCT BTG_RESOURCE_COLLECTION
    {
    STRUCT btg_sets[];
    STRUCT btg_buttons[];
    }

// EIKEDWIN.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//


# 44 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\uikon.rh"

STRUCT EDWIN
    {
    LONG flags=0;
    WORD width=0;
    WORD lines=1;
    WORD maxlength=0;
	WORD default_case= 0x4 ;	WORD allowed_case_modes= 0x1  | 0x2  | 0x4  ;	WORD numeric_keymap=EAknEditorAlphanumericNumberModeKeymap;	WORD allowed_input_modes= 0x1  | 0x2  | 0x4  | 0x8  | 0x10  | 0x20  | 0x40  | 0x80  | 0x200  ;	WORD default_input_mode= 0x1 ;	LLINK special_character_table=-1;	WORD avkon_flags= 0x000 ;	WORD max_view_height_in_lines=0;	WORD base_line_delta=0;	WORD spare=0; 
    }

//#include <eikedwin.hrh>

// EIKIMAGE.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eiklabel.hrh>

STRUCT IMAGE
	{
	WORD horiz_align= 0x01 ;
	WORD vert_align= 0x00 ;
	LTEXT bmpfile="";
    WORD bmpid;
    WORD bmpmask=0xffff;
	LLINK extension=0;
	}

// EIKLABEL.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eiklabel.hrh>

STRUCT LABEL
    {
	WORD flags = 0;
	WORD horiz_align= 0x01 ;
	WORD vert_align= 0x00 ;
	WORD standard_font=EEikLabelFontNormal;
	WORD reserve_length=0;
    LTEXT txt;
    }

// EIKLBX.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT LISTBOX
	{
	BYTE version=0;
	WORD flags = 0;
	WORD height = 5;		// in items
	WORD width = 10;		// in chars
    LLINK array_id = 0;
	}

//#include <eiklbx.hrh>

// EIKMENU.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT HOTKEY
    {
    LONG command;
    LONG key;
    }

STRUCT HOTKEYS
    {
    STRUCT plain[];
    STRUCT control[];
    STRUCT shift_control[];
    }

STRUCT MENU_PANE
    {
    STRUCT items[]; // MENU_ITEMs
	LLINK extension=0;
    }

STRUCT MENU_ITEM
    {
    LONG command=0;
    LLINK cascade=0;
    LONG flags=0;
    LTEXT txt;
	LTEXT extratxt="";
	LTEXT bmpfile="";
    WORD bmpid=0xffff;
    WORD bmpmask=0xffff;
	LLINK extension=0;
    }

STRUCT MENU_BAR
    {
    STRUCT titles[]; // MENU_BAR_ITEMs
	LLINK extension=0;
    }

STRUCT MENU_TITLE
    {
    LLINK menu_pane;
    LTEXT txt;
    LONG flags=0;
	LTEXT bmpfile="";
    WORD bmpid=0xffff;
    WORD bmpmask=0xffff;
	LLINK extension=0;
    }

//#include <eikmenu.hrh>

// EIKMNBUT.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikcmbut.hrh>

STRUCT MNBUT
    {
	LLINK popout=0;
	BYTE version=0;
	WORD behavior=0;
	WORD layout=0; // ETextRightPictureLeft
	LTEXT helptxt="";
	LLINK extension=0;
    LTEXT txt="";
	LTEXT bmpfile="";
    WORD bmpid=0xffff;
    WORD bmpmask=0xffff;
    }

// EIKRUTIL.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

// Removed by Bill
//#include <eikfont.rh> // for STRUCT FONT

STRUCT NUMBER_INT8
	{
	BYTE value=0;
	}

STRUCT NUMBER_INT16
	{
	WORD value=0;
	}

STRUCT NUMBER_INT32
	{
	LONG value=0;
	}

// EIKTBAR.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eiktbar.hrh>

STRUCT TOOLBAR
    {
	WORD length=0;
	WORD breadth= 70 ;
	BYTE lines=1;
    LONG flags=0;
    STRUCT controls[];
	LLINK extension=0;
    }

STRUCT TOOLBAND
    {
	WORD length=0;
	WORD breadth= 25 ;
	BYTE lines=1;
    LONG flags= 0x01 ;
    STRUCT controls[];
	LLINK extension=0;
    }

STRUCT TBAR_CTRL
	{
	WORD type;
	WORD id=0;
	WORD flags=0;
	WORD length=0;
	STRUCT control;
	}

STRUCT TBAR_BUTTON
	{
	WORD type=0; // EEikCtCommandButton;
	WORD id=0;
	WORD flags=0;
	WORD length=0;
	BYTE version=0;
	WORD behavior=0;
	WORD layout=0; // ETextRightPictureLeft|EEikCmdButShareExcess
	LTEXT helptxt="";
	LLINK extension=0;
    LTEXT txt="";
	LTEXT bmpfile="";
    WORD bmpid=0xffff;
    WORD bmpmask=0xffff;
	}

STRUCT TBAR_PICBUT
	{			
	WORD type=EEikCtTwoPictureCommandButton;
	WORD id=0;
	WORD flags=0;
	WORD length=0;
	BYTE version=0;
	WORD behavior=0;
	WORD layout=0; // ETextRightPictureLeft|EEikCmdButShareExcess
	LTEXT helptxt="";
	LLINK extension=0;
    LTEXT txt="";
	LTEXT bmpfile="";
    WORD bmpid=0xffff;
    WORD bmpmask=0xffff;
    WORD bmpsecondid=0xffff;
    WORD bmpsecondmask=0xffff;
	}

// EIKCMBUT.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikcmbut.hrh>

STRUCT CMBUT
    {
	BYTE version=0;
	WORD behavior=0;
	WORD layout=0; // ETextRightPictureLeft|EEikCmdButShareExcess
	LTEXT helptxt="";
	LLINK extension=0;
	LTEXT txt="";
	LTEXT bmpfile="";
    WORD bmpid=0xffff;
    WORD bmpmask=0xffff;
    }

STRUCT PICMBUT
    {
	BYTE version=0;
	WORD behavior=0;
	WORD layout=0;	// ETextRightPictureLeft|EEikCmdButShareExcess
	LTEXT helptxt="";
	LLINK extension=0;
	LTEXT txt="";
	LTEXT bmpfile="";
    WORD bmpid=0xffff;
    WORD bmpmask=0xffff;
    WORD bmpsecondid=0xffff;
    WORD bmpsecondmask=0xffff;
    }

STRUCT TXTBUT
    {
	BYTE version=0;
	WORD behavior=0;
	WORD layout=0; // EFirstRightSecondLeft|EEikCmdButShareExcess
	LTEXT helptxt="";
	LLINK extension=0;
    LTEXT txt1="";
    LTEXT txt2="";
    }

STRUCT BMPBUT
    {
	BYTE version=0;
	WORD behavior=0;
	WORD layout=0; // ETextRightPictureLeft|EEikCmdButShareExcess
	LTEXT helptxt="";
	LLINK extension=0;
	LTEXT bmp1file="";
    WORD bmp1id=0xffff;
    WORD bmp1mask;
	LTEXT bmp2file="";
    WORD bmp2id=0xffff;
    WORD bmp2mask;
    }

// EIKCOLOR.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT COLOR
	{
	BYTE red;
	BYTE green;
	BYTE blue;
	}

STRUCT CTRL_COLOR
	{
	WORD logical_color;
	STRUCT color; // COLOR
	}

STRUCT COLORLIST
	{
	LLINK array_id=0;
	}

STRUCT EIKCOLORLIST
	{
	LLINK array_id=0;
	LLINK ext_id;
	}

//#include <eikcolor.hrh>

// EIKFONT.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikfont.hrh>

STRUCT FONT
	{
	LONG fontid; // a value from fontids.hrh
	WORD flags=0; // a combination of EGulFontFlagXxxxs
	}

STRUCT NAMED_FONT
	{
	LTEXT name;
	WORD height;	// in twips
	WORD flags=0; // a combination of EGulFontFlagXxxxs
	}

STRUCT AVKON_SYSTEM_FONT
	{
	LONG fontuid; // a value from fontids.hrh
	STRUCT named_font; // this must be a NAMED_FONT structure type
	}

// EIKLBBUT.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eiklbbut.hrh>

STRUCT LBBUT
    {
	WORD buttontype=0; // EEikCtCommandButton
	STRUCT button;
	LONG hotkey;
	BYTE flags=1; // EEikLabeledButtonShowHotKey
    }

// EIKPRIV.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT INT16
	{
	WORD value;
	}

// EIKPRTPV.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

// EIKDEF.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT RSS_SIGNATURE
    {
    LONG signature= 4 ;
    SRLINK self;
    }

STRUCT TBUF1	{ BUF<1> buf; }
STRUCT TBUF2	{ BUF<2> buf; }
STRUCT TBUF4	{ BUF<4> buf; }
STRUCT TBUF8	{ BUF<8> buf; }
STRUCT TBUF9	{ BUF<9> buf; }
STRUCT TBUF16	{ BUF<16> buf; }
STRUCT TBUF32	{ BUF<32> buf; }
STRUCT TBUF40	{ BUF<40> buf; }
STRUCT TBUF64	{ BUF<64> buf; }
STRUCT TBUF80	{ BUF<80> buf; }
STRUCT TBUF128	{ BUF<128> buf; }
STRUCT TBUF256	{ BUF<256> buf; }

STRUCT CONTROLS
	{
	LEN BYTE STRUCT controls[];
	}

STRUCT EIK_APP_INFO
    {
    LLINK hotkeys=0;
    LLINK menubar=0;
    LLINK toolbar=0;
    LLINK toolband=0;
    LLINK cba=0;	
    LLINK status_pane=0;
    }

STRUCT PAGESIZE
	{
	LONG width=0;
	LONG height=0;
	}

STRUCT VIEW_ID
	{
	LONG appuid;
	LONG viewuid;
	}

// EIKDIALG.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

// only buttons defined in Uikon

STRUCT DLG_BUTTONS
    {
	LONG flags= 0x01 ;
    STRUCT buttons[];
    }

STRUCT DLG_BUTTON
    {
	WORD id=0;
	WORD buttontype=0; // EEikCtCommandButton
	STRUCT button;
	LONG hotkey;
	BYTE flags=1;
	BYTE line=1;
    }

// EIKSPANE.RH
//
// Copyright (c) 1999 Symbian Ltd.  All rights reserved.
//

STRUCT STATUS_PANE_SYSTEM_MODEL				// System wide status pane declaration
	{
	STRUCT panes[];							// entire set of valid SPANE_PANEs
	LLINK default_layout;					// default STATUS_PANE_LAYOUT
	LLINK layouts[];						// entire set of STATUS_PANE_LAYOUTs
	}

STRUCT SPANE_PANE
	{
	LONG id;
	WORD flags= 0 ;
	WORD type;
	LLINK resource=0;
	}

STRUCT STATUS_PANE_LAYOUT
	{
	WORD position;
	STRUCT pane_tree;						// SPANE_LAYOUT_TREE_NODE root of the layout tree
	}

STRUCT SPANE_LAYOUT_TREE_NODE
	{
	LONG id=0;
	WORD flags;
	WORD size;
	STRUCT sub_panes[];						// SPANE_LAYOUT_TREE_NODE sub panes
	}

STRUCT STATUS_PANE_APP_MODEL				// Application specific status pane
	{
	LLINK layout= 0 ;		// STATUS_PANE_LAYOUT to use for this app
	STRUCT panes[];							// SPANE_PANE overrides to use for this app
	}

// EIKCBA.RH
//
// Copyright (c) 1998 Symbian Ltd.  All rights reserved.
//

STRUCT CBA
	{
	LONG flags= 0x01 ;
	WORD breadth=80; // !!! make this accessible from LAF
	LLINK related_buttons=0;
   	STRUCT buttons[];
	}

STRUCT CBA_BUTTON
	{
	BYTE version=0;
	WORD id=0;
   	LTEXT txt="";
	LTEXT bmpfile="";
  	WORD bmpid=0xffff;		// -1
    WORD bmpmask=0xffff;	// -1
	}

// Notifiers

STRUCT NOTIFIER_LIST
	{
	LONG dll_uid;
	
	LEN WORD STRUCT notifier_list[]; // notifier data
	}

STRUCT NOTIFIER_DATA
	{
	LONG notifier_uid;
	}



# 4 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikon.rh" 2



// EIKDIALG.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

// buttons are defined in Uikon

STRUCT DIALOG
    {
    LONG flags=0;
    LTEXT title="";
	LLINK pages=0;
    LLINK buttons=0;
    STRUCT items[];
	LLINK form=0;
    }

STRUCT DLG_LINE
    {
    WORD type;
    LTEXT prompt;
    WORD id=0;
	LONG itemflags=0;
    STRUCT control;
	LTEXT trailer="";
	LTEXT bmpfile = "" ;   // NEW AVKON bitmap filename 
	WORD bmpid = 0xffff ; // NEW AVKON icon image ID
	WORD bmpmask ;		// NEW AVKON icon mask ID
	LTEXT tooltip = "" ;	// NEW AVKON hint text for form line
    }

STRUCT DLG_LINE_INDIRECT
    {
    WORD type= -1 ;
	LLINK line;
    }

STRUCT PAGE
	{
	WORD id=0;
	LTEXT text;
	LTEXT bmpfile = "" ;   // NEW AVKON bitmap filename 
	WORD bmpid = 0xffff ; // NEW AVKON icon image ID
	WORD bmpmask ;		// NEW AVKON icon mask ID
	LLINK lines=0;
	LLINK form=0 ;	
	WORD flags=0 ;	
	}

STRUCT DIALOG_INDIRECT
    {
    LONG flags=0;
    LTEXT title;
	LLINK pages=0;
    LLINK buttons=0;
    WORD count= -1 ;
	LLINK main=0;
    }

STRUCT FORM
	{
	WORD flags=0 ;
	STRUCT items[] ;
	}

// EIKDTLBX.RH
//
// Copyright (c) 1998 Symbian Ltd.  All rights reserved.
//

STRUCT DTLBOX
	{
	WORD flags=0;
	WORD modelflags=0;
	WORD height=5;	// in items
	WORD width=0;	// in pixels
	}

// EIKFBROW.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikfbrow.hrh>

//STRUCT FBROW
//    {
//    WORD flags;
//    WORD num_visible_items;
//	WORD dir_tree_width;
//	WORD dir_contents_width;
//    }

// EIKCHLST.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//STRUCT CHOICELIST
//	{
  //  WORD flags=0;
 //   WORD maxdisplaychar=0;
//	LLINK array_id=0;
//	}

//#include <eikchlst.hrh>

// EIKFPREV.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//STRUCT FPREV
//    {
//	WORD width=0;
//	WORD height=0;
//    LTEXT txt;
//    }

// EIKIMGAR.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT IMAGE_ARRAY
	{
	WORD width=0;
	LLINK array_id=0;
	}

// EIKCAL.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikcal.hrh>

//
// calendar STRUCT
//

STRUCT CALENDAR
	{
	WORD flags=0; // a combination of EEikCalendarFlagXxxxxs
	BYTE nummonths;
	BYTE nummonthsperrowofmonths;
	WORD verticalspaceaboveyear;
	WORD verticalspacebetweenyearandtoprowofmonths;
	WORD verticalspacebetweeneachrowofmonths;
	WORD verticalspacebeneathbottomrowofmonths;
	WORD horizontalspaceoneachsideofmonthmatrix;
	WORD horizontalspacebetweeneachcolumnofmonths;
	WORD verticalspacebetweenmonthnameanddaynameinitials;
	WORD verticalspacebetweendaynameinitialsandtoprowofdays;
	WORD verticalspacebetweeneachrowofdays;
	WORD horizontalspacebetweeneachcolumnofdays;
	STRUCT yearfont; // FONT
	STRUCT monthfont;
	STRUCT weekdayinitialfont;
	STRUCT numeralfont;
	LTEXT textseparatingyearrange;
	}


// EIKCLOCK.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikclock.hrh>

//
// primitive STRUCTs
//

STRUCT POINT
	{
	WORD x;
	WORD y;
	}
/* by H.Domon,K3 19 Apr 2001
STRUCT CLOCK_SHADOW
	{
	BYTE donotchange=1;
	STRUCT color; // COLOR
	BYTE offsetX;
	BYTE offsetY;
	}

STRUCT NO_CLOCK_SHADOW
	{
	BYTE donotchange=0;
	}
by H.Domon,K3 19 Apr 2001
*/
STRUCT CLOCK_PEN_SOLID
	{
	BYTE donotchange=1;
	BYTE color; // COLOR	// By H.Domon,K3. 23 Aug 2001
	BYTE size;
	}
/* by H.Domon,K3 19 Apr 2001
STRUCT CLOCK_PEN_NULL
	{
	BYTE donotchange=0;
	}

STRUCT CLOCK_BRUSH_SOLID
	{
	BYTE donotchange=1;
	STRUCT color; // COLOR
	}

STRUCT CLOCK_BRUSH_NULL
	{
	BYTE donotchange=0;
	}

//
// general clock STRUCT
//

STRUCT CLOCK
	{
	BYTE type=EEikLocaleConformantClockTypeChangesFormatAccordingToLocale; // one of the EEikLocaleConformantClockTypeXxxxxs
	BYTE typeneverchanges=0;
	LLINK digitalresourceid; // DIGITAL_CLOCK
	LLINK analogresourceid; // ANALOG_CLOCK_WITH_MASKED_FACE or ANALOG_CLOCK_WITH_UNMASKED_FACE
	}

//
// digital clock STRUCTs
//

STRUCT DIGITAL_CLOCK_TEXT_SECTION_TEXT_BLOCK
	{
	LTEXT text;
	}

STRUCT DIGITAL_CLOCK_TEXT_SECTION
	{
	STRUCT font; // FONT
	STRUCT textcolor; // COLOR
	BYTE horizontalalignment; // one of the EEikResourceConstructedClockDigitalDisplayHorizontalTextAlignmentXxxxxs
	BYTE verticalalignment; // one of the EEikResourceConstructedClockDigitalDisplayVerticalTextAlignmentXxxxxs
	WORD horizontalmargin=0;
	WORD verticalmargin=0;
	LEN BYTE STRUCT textblocks[]; // DIGITAL_CLOCK_TEXT_SECTION_TEXT_BLOCKs - will each be interspersed with a flashing-block delimiter
	}

STRUCT DIGITAL_CLOCK
	{
	BYTE withsingleblackborder=1;
	WORD offsetfromuniversaltime=0;
	STRUCT shadow; // CLOCK_SHADOW or NO_CLOCK_SHADOW
	STRUCT backgroundcolor; // COLOR
	LEN BYTE STRUCT textsections[]; // DIGITAL_CLOCK_TEXT_SECTIONs
	}

//
// analog clock STRUCTs
//
by H.Domon,K3 19 Apr 2001
*/
STRUCT ANALOG_CLOCK_HAND_FEATURE_LINE
	{
	STRUCT pen; // CLOCK_PEN_SOLID or CLOCK_PEN_NULL
	STRUCT startpoint; // POINT
	STRUCT endpoint; // POINT
	}
/* by H.Domon,K3 19 Apr 2001
STRUCT ANALOG_CLOCK_HAND_FEATURE_POLY_LINE
	{
	STRUCT pen; // CLOCK_PEN_SOLID or CLOCK_PEN_NULL
	STRUCT brush; // CLOCK_BRUSH_SOLID or CLOCK_BRUSH_NULL
	BYTE closed;
	LEN BYTE STRUCT points[]; // POINTs
	}

STRUCT ANALOG_CLOCK_HAND_FEATURE_CIRCLE
	{
	STRUCT pen; // CLOCK_PEN_SOLID or CLOCK_PEN_NULL
	STRUCT brush; // CLOCK_BRUSH_SOLID or CLOCK_BRUSH_NULL
	STRUCT circlecenter; // POINT
	WORD radius;
	}

STRUCT ANALOG_CLOCK_HAND_FEATURE
	{
	BYTE type; // one of the EEikResourceConstructedClockAnalogDisplayHandFeatureXxxxxs
	STRUCT feature; // ANALOG_CLOCK_HAND_FEATURE_LINE, ANALOG_CLOCK_HAND_FEATURE_POLY_LINE, or ANALOG_CLOCK_HAND_FEATURE_CIRCLE depending on "type"
	}

STRUCT ANALOG_CLOCK_HAND
	{
	BYTE type; // one of the EEikResourceConstructedClockAnalogDisplayHandOneRevPerXxxxxs
	LEN BYTE STRUCT features[]; // ANALOG_CLOCK_HAND_FEATUREs
	}

STRUCT ANALOG_CLOCK_WITH_MASKED_FACE
	{
	BYTE withsingleblackborder=0;
	WORD offsetfromuniversaltime=0;
	STRUCT shadow; // CLOCK_SHADOW or NO_CLOCK_SHADOW
	LTEXT filecontainingface=""; // defaults to the system multi-bitmap file
	LONG faceid; // a value defined in a *.MBG file
	BYTE donotchange=1;
	LTEXT filecontainingfacemask=""; // defaults to the system multi-bitmap file
	LONG facemaskid; // a value defined in a *.MBG file
	LEN BYTE STRUCT hands[]; // ANALOG_CLOCK_HANDs
	}

STRUCT ANALOG_CLOCK_WITH_UNMASKED_FACE
	{
	BYTE withsingleblackborder=0;
	WORD offsetfromuniversaltime=0;
	STRUCT shadow; // CLOCK_SHADOW or NO_CLOCK_SHADOW
	LTEXT filecontainingface=""; // defaults to the system multi-bitmap file
	LONG faceid; // a value defined in a *.MBG file
	BYTE donotchange=0;
	LEN BYTE STRUCT hands[]; // ANALOG_CLOCK_HANDs
	}
by H.Domon,K3 19 Apr 2001
*/
// EIKCMBOX.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT COMBOBOX
	{
    WORD width; // in characters
	WORD maxlength;
	WORD maxarraysize;
	}

// EIKFPNE.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT FLPTED
	{
	WORD maxlength=18;
	DOUBLE min=-9.9e99;
	DOUBLE max=9.9e99;
	DOUBLE default=0; // if !(min<=default<=max), default = min.
	}

STRUCT FIXPTED
	{
	WORD decimalplaces=2;// arbitrary, = number of pence in the pound
	LONG min;
	LONG max;
	LONG default=0; // if !(min<=default<=max), default = min.
	}

STRUCT TWIPSED
	{
	LONG min=0;// but can be set negative
	LONG max;
	}

// EIKGYSEL.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT GRAYSEL
	{
    WORD flags=0;
	}

//#include <eikgysel.hrh>

// EIKHOPBT.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT HOROPBUT
	{
	WORD buttonSpacing=12;
	WORD textOnRight=0;
	LLINK array_id=0;
	}

STRUCT OPBUT
	{
    WORD id=0;
    LTEXT text;
	}

// EIKMFNE.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikmfne.hrh>

//
// primitive STRUCTs
//

STRUCT TIME
	{
	BYTE second=0;
	BYTE minute=0;
	BYTE hour=0;
	}

STRUCT DATE
	{
	BYTE day=0; // from 0 to 27/28/29/30 inclusive
	BYTE month=0; // from 0 to 11 inclusive
	WORD year;
	}

STRUCT TIME_AND_DATE
	{
	BYTE second=0;
	BYTE minute=0;
	BYTE hour=0;
	BYTE day=0; // from 0 to 27/28/29/30 inclusive
	BYTE month=0; // from 0 to 11 inclusive
	WORD year;
	}

STRUCT DURATION
	{
	LONG seconds=0; // must be greater than or equal to zero
	}

STRUCT TIME_OFFSET
	{
	LONG seconds=0;
	}

STRUCT LATITUDE_AND_LONGITUDE
	{
	LTEXT degreesign;
	LTEXT minutesign;
	LTEXT secondsign;
	LTEXT north;
	WORD keytomatchfornorth;
	LTEXT south;
	WORD keytomatchforsouth;
	LTEXT east;
	WORD keytomatchforeast;
	LTEXT west;
	WORD keytomatchforwest;
	}

STRUCT MFNE_SYMBOLIC_ITEM
	{
	LONG id;
	WORD keytomatch;
	LTEXT text;
	}

STRUCT CELL
	{
	WORD row=0;
	WORD col=0;
	}

//
// STRUCTs for the different types of field
//

STRUCT MFNE_SEPARATOR
	{
	LTEXT text;
	}

STRUCT MFNE_NUMBER
	{
	LONG min;
	LONG max;
	BYTE flags=0;
	}

STRUCT MFNE_SYMBOL
	{
	LEN BYTE STRUCT symbolicitems[]; // MFNE_SYMBOLIC_ITEMs
	}

//
// STRUCTs for the different types of mfne
//

STRUCT NUMBER_EDITOR
	{
	LONG min;
	LONG max;
	}

STRUCT RANGE_EDITOR
	{
	LONG min;
	LONG max;
	LTEXT separatortext="-";
	}

STRUCT CELL_RANGE_EDITOR
	{
	STRUCT minCell; // CELL
	STRUCT maxCell; // CELL
	LTEXT separatortext=":";
	}

STRUCT TIME_EDITOR
	{
	STRUCT minTime; // TIME
	STRUCT maxTime; // TIME
	BYTE flags=0; // permitted flags: EEikTimeWithout[Seconds][Hours]Field
	}

STRUCT DATE_EDITOR
	{
	STRUCT minDate; // DATE
	STRUCT maxDate; // DATE
	BYTE flags=0; // permitted flags: EEikDateWithoutPopoutCalendar
	}

STRUCT TIME_AND_DATE_EDITOR
	{
	STRUCT minTimeAndDate; // TIME_AND_DATE
	STRUCT maxTimeAndDate; // TIME_AND_DATE
	BYTE flags=0; // permitted flags: EEikTimeWithout[Seconds][Hours]Field|EEikDateWithoutPopoutCalendar
	LTEXT interveningtext=" ";
	}

STRUCT DURATION_EDITOR
	{
	STRUCT minDuration; // DURATION
	STRUCT maxDuration; // DURATION
	BYTE flags=0; // permitted flags: EEikTimeWithout[Seconds][Hours]Field
	}

STRUCT TIME_OFFSET_EDITOR
	{
	STRUCT minTimeOffset; // TIME_OFFSET
	STRUCT maxTimeOffset; // TIME_OFFSET
	BYTE flags=0; // permitted flags: EEikTimeWithout[Seconds][Hours]Field
	}

STRUCT LATITUDE_EDITOR
	{
	LONG flags=0;
	LLINK latlongresourceid; // LATITUDE_AND_LONGITUDE
	}

STRUCT LONGITUDE_EDITOR
	{
	LONG flags=0;
	LLINK latlongresourceid; // LATITUDE_AND_LONGITUDE
	}

// EIKPROGI.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT PROGRESSINFO
 	{
    WORD text_type=0;
	WORD splits_in_block=0;
	LONG finalval;
	LONG width=120;
	LONG height=10;
	}

//#include <eikprogi.hrh>

// EIKRTED.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikrted.hrh>
//#include <eikgted.hrh>
# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\gulftflg.hrh" 1
// GULFTFLG.HRH
//
// Copyright (c) Symbian Software Ltd 1997 - 2004. All rights reserved.
//

/** Maximum length for text selection.
@publishedAll 
@released 
*/


/** All font controls.
@publishedAll 
@released 
*/


/** Font control name.
@publishedAll 
@released 
*/


/** Font control size.
@publishedAll 
@released 
*/


/** Bold font control.
@publishedAll 
@released 
*/


/** Italic font control.
@publishedAll 
@released 
*/


/** Underline font control.
@publishedAll 
@released 
*/


/** Strikethrough font control.
@publishedAll 
@released 
*/


/** Font text color control.
@publishedAll 
@released 
*/


/** Print position font control.
@publishedAll 
@released 
*/


/** All fonts.
@publishedAll 
@released 
*/


/** Monospace fonts only.
@publishedAll 
@released 
*/


/** No monospace fonts.
@publishedAll 
@released 
*/


/** Symbol fonts only.
@publishedAll 
@released 
*/


/** No symbol fonts.
@publishedAll 
@released 
*/


/** No monospace or symbol fonts.
@publishedAll 
@released 
*/

# 589 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\eikon.rh" 2


STRUCT RTXTED
    {
	WORD width=0;
	WORD height=0;
	WORD numlines=1;
	WORD textlimit=0;
	LONG flags=0;
	WORD fontcontrolflags=1;
	WORD fontnameflags= 0x10 ;
	WORD default_case= 0x4 ;	WORD allowed_case_modes= 0x1  | 0x2  | 0x4  ;	WORD numeric_keymap=EAknEditorAlphanumericNumberModeKeymap;	WORD allowed_input_modes= 0x1  | 0x2  | 0x4  | 0x8  | 0x10  | 0x20  | 0x40  | 0x80  | 0x200  ;	WORD default_input_mode= 0x1 ;	LLINK special_character_table=-1;	WORD avkon_flags= 0x000 ;	WORD max_view_height_in_lines=0;	WORD base_line_delta=0;	WORD spare=0; 
    }

// EIKSECED.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT SECRETED
	{
 	WORD num_letters=8;
	}

// EIKSPACE.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikspace.hrh>

STRUCT SPACER
    {
	WORD width=0;
	WORD height=0;
	LONG color=0; // clear
    }

// EIKWSEL.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT WORLD_SELECTOR
	{
	WORD flags=0;
	WORD chars_wide=0;
	LTEXT countrysearch="";
	LTEXT worldsearch="";
	}

//#include <eikwsel.hrh>
// EIKDLGTB.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

//#include <eikctrls.hrh>

STRUCT DLG_TOOLBAR
    {
	WORD width=0;
    STRUCT controls[];
    }

STRUCT DLG_TBAR_BUTTON
	{
	WORD type=1; // EEikCtLabeledButton
	WORD id=0;
	WORD flags=0;
	WORD length=0;
	WORD buttontype=0; // EEikCtCommandButton
	STRUCT button;
	LONG hotkey;
	BYTE hotkeyflags=1; // EEikLabeledButtonShowHotKey
	}

STRUCT DLG_TBAR_SPACER
	{
	WORD type=EEikCtSpacer;
	WORD id=0;
	WORD flags=0;
	WORD length=0;
	WORD width=0;
	WORD height=0;
	LONG color=0; // clear
	}

STRUCT DLG_TBAR_CTRL
	{
	WORD type;
	WORD id=0;
	WORD flags=0;
	WORD length=0;
	STRUCT control;
	}
// EIKPRTPV.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT PRTPREV
    {
    WORD width;
    WORD height;
    }

// EIKFSEL.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT FILENAMESELECTOR
	{
	WORD maxdisplaychar=15;
	}

STRUCT FILENAMEEDITOR
	{
    WORD width = 15;
	}

STRUCT FOLDERNAMESELECTOR
	{
	WORD maxdisplaychar=15;
	}

STRUCT FOLDERNAMEEDITOR
	{
    WORD width = 15;
	}

STRUCT DRIVENAMESELECTOR
	{
	}

// EIKGTED.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

STRUCT GTXTED
    {
	WORD width=0;
	WORD height=0;
	WORD numlines=1;
	WORD textlimit=0;
	LONG flags=0;
	WORD fontcontrolflags=1;
	WORD fontnameflags= 0x10 ;
	WORD default_case= 0x4 ;	WORD allowed_case_modes= 0x1  | 0x2  | 0x4  ;	WORD numeric_keymap=EAknEditorAlphanumericNumberModeKeymap;	WORD allowed_input_modes= 0x1  | 0x2  | 0x4  | 0x8  | 0x10  | 0x20  | 0x40  | 0x80  | 0x200  ;	WORD default_input_mode= 0x1 ;	LLINK special_character_table=-1;	WORD avkon_flags= 0x000 ;	WORD max_view_height_in_lines=0;	WORD base_line_delta=0;	WORD spare=0; 
    }

// EIKUFSEL.RH
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//


STRUCT UNIFIEDNAMESELECTOR
	{
	WORD maxdisplaychar=15;
	}

//
// Resource structure for CAknIpFieldEditor
// 

STRUCT IP_FIELD_EDITOR
	{
	STRUCT min_field_values;
	STRUCT max_field_values;
	BYTE flags;		
	}

STRUCT IP_FIELD
	{
	BYTE first_field;
	BYTE second_field;
	BYTE third_field;
	BYTE fourth_field;
	}
# 16 "C:\\KG\\LESSA\\Symbian\\data\\LESSA.rss" 2

# 1 "C:\\KG\\LESSA\\Symbian\\inc\\LESSA.hrh" 1
/*
============================================================================
 Name        : LESSA resource header file LESSA.hrh
 Author      : 
 Version     :
 Copyright   : Your copyright notice
 Description : This file contains declarations for constants of LESSA.
               The file can be included in C++ or resource file.
============================================================================
*/




enum TLESSACommandIds
    {
    ELESSACmdAppTest = 1
    };

enum TLESSATabViewId
    {
    ELESSAView1Tab= 1,
    ELESSAView2Tab
    };
 




// LESSA_HRH
# 17 "C:\\KG\\LESSA\\Symbian\\data\\LESSA.rss" 2

# 1 "C:\\KG\\LESSA\\Symbian\\inc\\LESSA.loc" 1
/*
============================================================================
 Name        : LESSA.loc
 Author      : 
 Version     :
 Copyright   : Your copyright notice
 Description : This is a localisation file for LESSA
               A .loc file is the one and only place where the logical
			   strings to be localised are defined. 
============================================================================
*/

// LOCALISATION STRINGS

//d:Command in options menu.
//d:Example application spesific command.
//l:list_single_popup_submenu_pane_1
//


// menu exit


//d:Command in options menu.
//d:Example application spesific command.
//l:list_single_popup_submenu_pane_1
//


//d:Command in options menu.
//d:Example command for view 1.
//l:list_single_popup_submenu_pane_1
//


//d:Command in options menu.
//d:Example command for view 2.
//l:list_single_popup_submenu_pane_1
//


//d:Name of the view 1 tab.
//d:
//l:
//


//d:Name of the view 2 tab.
//d:
//l:
//


// example caption strings for app





# 18 "C:\\KG\\LESSA\\Symbian\\data\\LESSA.rss" 2

# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\avkon.rsg" 1









































































































































































































































































































































































































# 19 "C:\\KG\\LESSA\\Symbian\\data\\LESSA.rss" 2

# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\avkon.rh" 1
/*
* ============================================================================
*  Name     : Avkon.rh
*  Part of  : Avkon
*
*  Description:
*     Resource structure definitions for Avkon 
*  Version:
*
*  Copyright © 2002 Nokia Corporation.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia Corporation. All rights are reserved. Copying, 
*  including reproducing, storing,  adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia Corporation. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia Corporation.
* ============================================================================
*/

# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\avkon.hrh" 1
/*
* ============================================================================
*  Name     : Avkon.hrh
*  Part of  : Avkon
*
*  Description:
*     Constants for Avkon that may need to be used in resource files
*  Version:
*
*  Copyright © 2002 Nokia Corporation.
*  This material, including documentation and any related
*  computer programs, is protected by copyright controlled by
*  Nokia Corporation. All rights are reserved. Copying,
*  including reproducing, storing,  adapting or translating, any
*  or all of this material requires the prior written consent of
*  Nokia Corporation. This material also contains confidential
*  information which may not be disclosed to others without the
*  prior written consent of Nokia Corporation.
* ============================================================================
*/








# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\aknfontcategory.hrh" 1
/*
* ============================================================================
*  Name     : AknFontCategory.hrh
*  Part of  : FontUtils
*  Description : Avkon font categories correspond to the font "Category types" in the 
*  Series60 layout tool
*
*  Copyright © 2002-2004 Nokia. All rights reserved.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia. All rights are reserved. Copying, including 
*  reproducing, storing, adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia.
* ==============================================================================
*/





/**
* Definition of Series 60 logical font categories. 
* Note: These are not logical font ids
* 
* @since Series 60 2.8
*/







enum TAknFontCategory
	{
	EAknFontCategoryUndefined =		0 ,
	EAknFontCategoryPrimary =		1 ,
	EAknFontCategorySecondary =		2 ,
	EAknFontCategoryTitle =			3 ,
	EAknFontCategoryPrimarySmall =	4 ,
	EAknFontCategoryDigital =		5 
	};



// End of File
# 29 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\avkon.hrh" 2

# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\aknfontidoffsets.hrh" 1
/*
* ============================================================================
*  Name     : AknFontIdOffsets.h
*  Part of  : FontUtils
*
*  Description: Constants and offsets for Scalable and Encoded Font IDs
*
*  Copyright © 2002-2004 Nokia. All rights reserved.
*  This material, including documentation and any related 
*  computer programs, is protected by copyright controlled by 
*  Nokia. All rights are reserved. Copying, including 
*  reproducing, storing, adapting or translating, any 
*  or all of this material requires the prior written consent of 
*  Nokia. This material also contains confidential 
*  information which may not be disclosed to others without the 
*  prior written consent of Nokia.
* ==============================================================================
*/




/**
* Constants and Offsets for Scalable and Encoded Font IDs
*/

// Constant to form the base value for the definition of Logical fonts

// This constant is retained for binary compatibility




enum {EScalableFontIdOffset = (0x1000)  };

// Interface from layout apis is 16 bit. "Lowest" is defined in an unsigned context



// Define lowest end of range of IDs to be generated by toolchain
// Start at Scalable ID offset, but leave space for all the "lay scaled" IDs



// End of File
# 30 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\avkon.hrh" 2


//
// This file is very important for applications!
//
// Here we have many names you can find from Series 60 specifications
// This file provides access for applications to the following services:
//   * Selection Service
//   * Find
//

// internal, do not use (maybe you might need to use LoopScrolling though, but use it with some other flags...)






// Note there's also EAknListBoxViewerFlags, which is better for apps.


// These are combined to the viewerflag to make it fit to WORD in resources.



// The next ones are used internally by SingleGraphicStyle and DoubleGraphicStyle





// Implementation detail, do not use - for dialog flags


//
//
//  SELECTION SERVICE IMPLEMENTATION STARTS HERE (Use these in applications!)
//
// LISTBOX FLAGS (use these in applications)
//















//
// Viewers (see Selection service)
//


//
// DIALOG FLAGS (applications should use these!)
//








// Flags for note dialogs:









// Flags for query dialogs:





//
// CBA LABELS (applications should use these)
//










//
// Menu panes (context specific menu panes)
//






//
// There are also ready-made HandleCommandL() implementations for selection service in aknutils.h
//
// AknSelectionService::HandleSelectionListProcessCommandL(aCommand, iListBox);
// AknSelectionService::HandleMultiSelectionListProcessCommandL(aCommand, iListBox);
// AknSelectionService::HandleMarkableSelectionListProcessCommandL(aCommand, iListBox);
//

//
// Application icon dimensions (for proper layout in Application Shell and Fast Application Swap)
//

enum
    {
    EAknApplicationIconWidth = 42,
    EAknApplicationIconHeight = 29
    };

//
//
//  SELECTION SERVICE IMPLEMENTATION ENDS HERE
//
//


//
// FIND IMPLEMENTATION STARTS HERE, use AknFind with these.
//

// Options menu. Use these instead of R_AVKON_MENUPANE_[SELECTION|MARKABLE]_LIST when find popup window is needed





//
// FIND IMPLEMENTATION ENDS HERE
//




// for ProcessCommandL()
enum
    {
    EAknDummyForProcessCommands=4000,
    EAknMarkAll, // selection service impl
    EAknUnmarkAll, // selection service impl
    EAknCmdHelp,
    EAknCmdAddToPinboard,
    EAknCmdFindPopupActivated,
    EAknCmdEditModeT9,
    EAknCmdEditModeMultitap,
    EAknCmdEditModeNumber,
    EAknCmdEditInsertNumber,
    EAknCmdEditInsertSymbol,
    EAknCmdInputLanguage,
    EAknCmdPredictiveTextCascade,
    EAknCmdT9PredictiveMatches,
    EAknCmdT9PredictiveInsertWord,
    EAknCmdT9PredictiveEditWord,
    EAknCmdT9PredictiveT9Off,
    EAknCmdMultitapPredictiveT9On,
    EAknCmdExit,
    EAknCmdEditTextMenu,
    EAknCmdEditListMenu, // selection service impl
    EAknCmdMark, // selection service impl
    EAknCmdUnmark, // selection service impl
    EAknCmdOpen,    // selection service impl

    // command ids for APAC build
    EChinFepCmdInstructions,
    EChinFepCmdModePinyin,
    EChinFepCmdModeZhuyin,
    EChinFepCmdModeStroke,
    EChinFepCmdModeLatinUpper,
    EChinFepCmdModeLatinLower,
    EChinFepCmdModeNumber,
    EChinFepCmdModeZhuyinFind,
    EChinFepCmdModeStrokeFind,

    EAknCmdEditModeArabicIndicNumber,
    EAknCmdEditModeAlpha,
    EAknCmdEditModeLatinText,

    // command ids for Japanese build
    EJapanFepCmdModeHiragana,
    EJapanFepCmdModeKatakana,
    EJapanFepCmdModePictographs,
    EJapanFepCmdModeFullWidth,
    EJapanFepCmdModeHalfWidth,
    EJapanFepCmdModePredictiveOn,
    EJapanFepCmdModePredictiveOff,
    EJapanFepCmdModeUserDic,
    EJapanFepCmdModeKutenCodeInput,
    EAknCmdEditInsertPictograph,
    EJapanFepCmdPredictiveTextCascade,
    EJapanFepCmdMultitapPredictiveT9On,
    EJapanFepCmdEditModeAlpha,
    EJapanFepCmdEditModeNumber,

    EAknCmdEnd
};

/**
* Note that although these are the command ids resulting from the CBA key press, codes returned from
* CAknDialog::ExecuteLD are mapped in the routine CEikDialog::MappedCommandId.  This routine should be consulted
* before knowing what the dialog will return.
*/
enum        // CBA constants
    {
    EAknSoftkeyOk = -2 ,
    EAknSoftkeyCancel = -1 ,
    EAknSoftkeySelect = -6 ,
    EAknSoftkeyOptions= 3000,
    EAknSoftkeyBack,
    EAknSoftkeyMark,
    EAknSoftkeyUnmark,
    EAknSoftkeyInsert,
    EAknSoftkeyYes,
    EAknSoftkeyNo,
    EAknSoftkeyDone,
    EAknSoftkeyClose,
    EAknSoftkeyExit,
    EAknSoftkeyClear,
    EAknSoftkeyUnlock,
    EAknSoftkeySave,
    EAknSoftkeyShow,
    EAknSoftkeyListen,
    EAknSoftkeyRead,
    EAknSoftkeySearch,
    EAknSoftkeyEmpty,
    EAknSoftkeyLock,
    EAknSoftkeyCall,
    EAknSoftkeyAgain,
    EAknSoftkeyQuit,
    EAknSoftkeyDetails,
    EAknSoftkeyNext,
    EAknSoftkeyOther
    };

enum    {
    EAknSoftkeyDummyUsedWithShortcuts = 3200
    };

enum
    {
    EAknCBAFlagRespondWhenInvisible = 0x02   // softkeys still respond to key events even when control is invisible
    };


// Predefined softkey ranges for supporting limited automatic control of such things as
// return from dialog-like contexts.
// All dialog-like contexts should  return 0 for values in the first range.
// CEikDialog does not use the other implied ranges at all.
// Other contexts may use the "accept" range for internal behaviour






// Define a Cba version number of differentiate from GT CBA
// Current GT version is 0, but it's worth avoiding 1,2 etc in
// case of future incompatibilities.


//
//
// Avkon control id's start from 5700
// Phonebook control id's start from 6000

//
// Avkon Control Type codes
//



enum
    {
    EAknCtTest = 5699 ,
    EAknControlIdBase = 5700,

    EAknCtFormattedListBox, // generic formatted listbox

    // "General list pane descendants"
    EAknCtSingleListBox,
    EAknCtSingleNumberListBox,
    EAknCtSingleHeadingListBox,
    EAknCtSingleGraphicListBox,
    EAknCtSingleGraphicHeadingListBox,
    EAknCtSingleNumberHeadingListBox,
    EAknCtSingleLargeListBox,
    EAknCtDoubleListBox,
    EAknCtDoubleNumberListBox,   // this is also big number implementation
    EAknCtDoubleTimeListBox,
    EAknCtDoubleLargeListBox,  // this is also big large graphic implementation
    EAknCtDoubleGraphicListBox,
    EAknCtSettingListBox,     // this is also big setting pane implementation
    EAknCtSettingNumberListBox,  // this is also big setting number pane implementation

    // "Pop up window list pane descendants"
    EAknCtSinglePopupMenuListBox,
    EAknCtSingleGraphicPopupMenuListBox,
    EAknCtSingleGraphicHeadingPopupMenuListBox,
    EAknCtMenuDoublePopupMenuListBox,
    EAknCtSinglePopupSubmenuListBox,
    EAknCtDoubleLargeGraphicPopupMenuListBox,
    EAknCtSingleHeadingPopupMenuListBox,

    // "List pane elements and descendants(settings, edited)"
    EAknSetListBox,

    // "List pane elements (form, popup)"
    EAknFormGraphicListBox,

    // These are listboxes too.
    EAknCtAppGrid,
    EAknCtPinbGrid,      // This is provided as example only.
    EAknCtQdialGrid,     // this is provided as example only.
    EAknCtCaleMonthGrid, // this is provided as example only.

    // Avkon Status pane controls
    EAknCtTitlePane,
    EAknCtContextPane,
    EAknCtNaviPane,
    EAknCtSignalPane,
    EAknCtBatteryPane,
    EAknCtIndicatorPane,
    EAknCtIdleContextPane,
//
//  For AVKON notes and queries:
//
    EAknCtNote,
    EAknCtQuery,
    EAknCtMultilineQuery,
//
// For AVKON popup field:
//
    EAknCtPopupField,
    EAknCtPopupFieldText,
// For AVKON Form
    EAknCtFormLabelEditor,

// For LAF reader
    EAknCtLAF,
    EAknCtPopupHeadingPane,
    EAknCtSearchField,

//  For Setting Page
    EAknCtSettingPage,

// For AknVolumeControl and AknSlider
    EAknCtVolumeControl,
    EAknCtSlider,
    EAknCtListQueryControl,
    EAknCtSpecialCharacterMap,

// For AknPhoneNumberEditor
    EAknPhoneNumberEditor,

// Numeric secret editor
    EAknCtNumericSecretEditor,

// Popup Setting List Page
    EAknCtPopupSettingList,
// Message query
    EAknCtMessageQuery,

// Specialized numeric edwins
    EAknCtIntegerEdwin,
    EAknCtFloatingPointEdwin,
    EAknCtSelectionListFixedFind,
    EAknCtSelectionListPopupFind,
    EAknCtEmptyList,
    EAknCtDouble2GraphicListBox,
    EAknCtDouble2LargeListBox,
    EAknCtDouble2PopupMenuListBox,

// NOTE: DO NOT USE THESE LISTS (break ui-style, only for java)!!!
    EAknCtSingle2GraphicListBox,
    EAknCtDouble2GraphicLargeListBox,
// END OF NOTE

// Colour selection grid
    EAknCtColourSelectionDialogNoneField,
    EAknCtColourSelectionDialogGrid,

// Find box in list query dialog
    EAknCtListQuerySearchControl,

// Derived query control for ip & fixed point queries
    EAknExtCtQuery,

// Derived multiline query control for ip&ip queries
    EAknExtCtMultilineQuery,

   EAknCtBitmapAnimation,

// This is the marker for the last AVKON control id: It does not construct a control
    EAknCtLastControlId = 0x2000 

//  Control ids beyond (or including) this value will be dealt with as custom controls.

//  However, to assist collaboration between applications, the following Series 60 -specific
//  application- related ranges are documented here:
//
//  Phonebook- related control ids = 0x2800 - 0x2C00
//
//  Applications which do not have to correlate with any other DLLs or apps, should use the
//  range 0x2001 - 0x2800
//

// Control ID range 0xF000 - 0xFFFF is reserved for licensee controls.

    };

// Navi decorator control types
enum
    {
    ENaviDecoratorControlNone,
    ENaviDecoratorControlTabGroup,
    ENaviDecoratorLabel,
    ENaviDecoratorImage,
    ENaviDecoratorToolTip // Hint text
    };

// Navigation pane tab width specifiers


enum
    {
    EAknTabWidthWithTwoTabs = 36,
    EAknTabWidthWithTwoLongTabs = 74,
    EAknTabWidthWithThreeTabs = 22,
    EAknTabWidthWithThreeLongTabs = 67,
    EAknTabWidthWithFourTabs = 18,
    EAknTabWidthWithOneTab = 107
    };

// Note dialog constants
enum
    {
    EGeneralLayout = 1,
    EConfirmationLayout,
    EProgressLayout,
    ENoteWithImageLayout,
    ETextualNotificationLayout,
    ENotificationWithGraphicsLayout,
    EAknNoteControlAnimationCreationFailed,
    EWaitLayout
    };

enum
    {
    EAknInvalidBorderCount = 1,
    EAknInvalidDimensionArrayOutOfBounds,
    EAknNoNoteControlDimensionDefined,
    EAknNoteControlNullArgumentUsed
    };

enum EAknNoteItemType {
    EAknNoteNoType = 1,
    EAknNoteBitmap,
    EAknNoteNumberTypeIndication,
    EAknNoteProgressBar,
    EAknNoteLabel,
    EAknNoteAnimation
};

enum TNoteCtrlIds
    {
    EGeneralNote = 1
    };


//Note control flags



// Query dialog constants

// These are query types, and each type must be mapped
// to a layout (e.g. code layout or data layout)
// If you add or change a type here you need to update
// KQueryTypeToLayout in aknquerycontrol.cpp otherwise
// query control will crash with EAknPanicNotSupported
// because the layout is not known
enum
    {
    EDataLayout=1,
    EConfirmationQueryLayout,
    ECodeLayout,
    ETimeLayout,
    EDateLayout,
    EListLayout,
    EMultiListLayout,
    EMultiLineDataLayout,
    EDurationLayout,
    ETextSoftNotification,
    ENumberLayout,
    EPinLayout,
    EPhoneLayout,
    EMessageQueryLayout,
    EStaticSizeDataLayout,
    EFloatingPointLayout,
    EIpLayout,
    EFixedPointLayout,
    EDataLayoutAllowEmptyInput
    };

enum
    {
    ETextEditor=1,
    ESecretEditor,
    ETimeEditor,
    EDateEditor,
    ENumberEditor,
    EDurationEditor,
    EIpEditor,
    EFixedPointEditor
    };

enum EAknMultilineDataLayout
{
    EMultiDataFirstEdwin = 1,
    EMultiDataSecondEdwin,
    EMultiDataFirstSecEd,
    EMultiDataSecondSecEd,
    EMultiDataFirstTimeEd,
    EMultiDataSecondTimeEd,
    EMultiDataFirstDateEd,
    EMultiDataSecondDateEd,
    EMultiDataFirstDurEd,
    EMultiDataSecondDurEd,
    EMultiDataFirstPhoneEd,
    EMultiDataSecondPhoneEd,
    EMultiDataFirstNumEd,
    EMultiDataSecondNumEd,
    EMultiDataFirstPinEd,
    EMultiDataSecondPinEd,
    EMultiDataFirstIpEd,
    EMultiDataSecondIpEd
    };

enum TQueryCtrlIds
    {
    EGeneralQuery = 0x500,
    EMultilineFirstLine,
    EMultilineSecondLine
    };

enum TListQueryCtrlIds
    {
    EListQueryMainInboxList = 1,
    EListQueryMainDraftList,
    EListQueryMainOutboxList,
    EListQueryAppViewLabel,
    EListQueryMsgEditField,
    EListQueryHeading,
    EListQueryControl
    };

enum TSelectionListCtrlIds
    {
    ESelectionListControl = 1,
    EFindControl,
    EAknEmptyListControl,
    EAknListQueryMessageBox
    };


// layout commands (for lists currently)
enum
    {
    ELayoutNoCmd =1,
    ELayoutOptional, // optional items
    ELayoutRightSeparator, // adds separator
    ELayoutTransparentCell,  // transparent cell for formattedlistbox only
    ELayoutItemMark,         // sets column/subcell to handle item mark in multiselection lists

    ELayoutNotFilled,
    ELayoutNotAlwaysDrawn
    };

enum {
    ELayoutAlignNone,
    ELayoutAlignCenter,
    ELayoutAlignLeft,
    ELayoutAlignRight,
    ELayoutAlignBidi
     };

// Editor alignment
enum
    {
    EAknEditorAlignNone = ELayoutAlignNone,
    EAknEditorAlignCenter = ELayoutAlignCenter,
    EAknEditorAlignLeft = ELayoutAlignLeft,
    EAknEditorAlignRight = ELayoutAlignRight,
    EAknEditorAlignBidi = ELayoutAlignBidi
     };

// Editor character case
enum
    {
    EAknEditorCharactersUpperCase = 0x1 ,
    EAknEditorCharactersLowerCase = 0x2 ,
    EAknEditorCharactersTextCase = 0x4 
    };


/**
*
* Series 60 pre-2.8 Font Ids
*
*/

enum {
    EFontNone = 0,
    ELatinPlain12,
    ELatinBold12,
    ELatinBold13,
    ELatinBold17,
    ELatinBold19,
    ENumberPlain5,
    EClockBold30,
    ELatinClock14,
    EFontCustom,
    EPlain12,
    EPlain16,
    EApacPlain12 = EPlain12,
    EApacPlain16 = EPlain16,
    EBold18,
    EBold24,
    ELatinBold16,
    ECalcBold21,
    ECalcOperBold21,
    ECalcOperBold13,
	EHighestFixedLayoutFont = ((0x100-1) ) 
    };

/**
* Series 60 Logical Fonts
*
* @since Series 60 2.6
*/

enum TAknLogicalFontId
	{
	EAknLogicalFontPrimaryFont = ((0x100-1) )   + 1 ,
	EAknLogicalFontSecondaryFont= ((0x100-1) )  + 2 ,
	EAknLogicalFontTitleFont= ((0x100-1) )  + 3 ,
	EAknLogicalFontPrimarySmallFont= ((0x100-1) )  + 4 ,
	EAknLogicalFontDigitalFont= ((0x100-1) )  + 5 ,
	EAknHighestLogicalFont = ((0x1000) -1) 
	};




// For layout resource of findbox
enum
{
    EAknLayoutFindPaneIconId = 1,
    EAknLayoutFindPaneEditorId,
    EAknLayoutMainPaneListGenPane,
    EAknLayoutMainPaneListGenPaneWithFindBox,
    EAknLayoutMainPaneFindPane,

    EAknListSinglePane,
    EAknListSingleNumberPane,
    EAknListSingleHeadingPane,
    EAknListSingleGraphicPane,
    EAknListSingleGraphicHeadingPane,
    EAknListSingleNumberHeadingPane,
    EAknListSingleLargeGraphicPane,
    EAknListDoubleNumberPane,
    EAknListDoubleTimePane,
    EAknListDoubleLargeGraphicPane,
    EAknListDoubleGraphicPane,
    EAknListSettingNumberPane,


    EAknLayoutFindPaneVShadow,
    EAknLayoutFindPaneHShadow,
    EAknLayoutFindPaneOutlineRect,


    EAknLayoutEmptyList1stLine,
    EAknLayoutEmptyList2ndLine
};


// Status pane pane Uids










// POPUP_FIELD flags





enum
    {
    EAknDialogQueryValueTextEditor1 = 1,
    EAknDialogQueryValueNumberEditor1,
    EAknDialogQueryValuePhoneEditor1,
    EAknDialogQueryValueTimeEditor1,
    EAknDialogQueryValueDateEditor1,
    EAknDialogQueryValueDurationEditor1,
    EAknFormQueryControl,
    EAknPopupFieldEmptyListNote
    };

// POPUP_SETTING_LIST flags
enum
    {
    EAknPopupSettingListFlagAllowsUserDefinedEntry = 0x001,
    EAknPopupSettingListFlagInitialised = 0x002
    };

// FORM default menu constants
enum
    {
    EAknFormCmdEdit = 950,
    EAknFormCmdAdd,
    EAknFormCmdSave,
    EAknFormCmdLabel,
    EAknFormCmdDelete,
    EAknFormMaxDefault
    };

// Slider layouts
enum
    {
    EAknFormSliderLayout1 =1,
    EAknFormSliderLayout2,
    EAknFormSliderLayout3,
    EAknSettingsItemSliderLayout,
    EAknSettingsItemSliderLayoutWithGraphics,
    EAknMIDPFormSliderLayout
    };

// Slider value types
enum
    {
    EAknSliderValueNone,
    EAknSliderValueBareFigure,
    EAknSliderValuePercentage,
    EAknSliderValueFraction,
    EAknSliderValueDecimal
    };

// Volume layouts
enum
    {
    ESettingsVolumeControl,
    ENaviPaneVolumeControl,
    EPopupVolumeControl
    };

// Small indicator pane indicators & navi pane editor indicators
enum
    {
    // Status pane's indicator pane's indicators.
    EAknIndicatorIrActive,
    EAknIndicatorEnvelope,
    EAknIndicatorEmailMessage,
    EAknIndicatorDataMessage,
    EAknIndicatorFaxMessage,
    EAknIndicatorOtherMessage,
    EAknIndicatorSecuredConnection,
    EAknIndicatorVoiceMailWaiting,
    EAknIndicatorVoiceMailWaitingOnLine1,
    EAknIndicatorVoiceMailWaitingOnLine2,
    EAknIndicatorVoiceMailWaitingOnBothLines,
    EAknIndicatorHomeZone,
    EAknIndicatorBluetooth,
    EAknIndicatorBluetoothModuleOn,
    EAknIndicatorOutbox,
    EAknIndicatorKeyguard,
    EAknIndicatorAllCallsForwarded,
    EAknIndicatorCallsForwardedOnLine1,
    EAknIndicatorCallsForwardedOnLine2,
    EAknIndicatorCallsForwardedOnBothLines,
    EAknIndicatorCallsForwardedToVoiceMailbox,
    EAknIndicatorSelectedLine,
    EAknIndicatorAlarmClock,
    EAknIndicatorHeadset,
    EAknIndicatorLoopset,
    EAknIndicatorIHFActive,
    EAknIndicatorInstantMessage,
    EAknIndicatorTTY,
    EAknIndicatorUSBConnection,
    EAknIndicatorMissedCalls,
    EAknIndicatorRemoteMailboxEmailMessage,
    EAknIndicatorLocation,
    EAknIndicatorHeadsetUnavailable,
    EAknIndicatorRoaming,
    EAknIndicatorLocationOn,
    EAknIndicatorLocationOff,
    EAknIndicatorPoC,

    // Navi pane editor indicators
    EAknNaviPaneEditorIndicatorT9 = 100,
    EAknNaviPaneEditorIndicatorUpperCase,
    EAknNaviPaneEditorIndicatorLowerCase,
    EAknNaviPaneEditorIndicatorTextCase,
    EAknNaviPaneEditorIndicatorNumberCase,
    EAknNaviPaneEditorIndicatorQuery,
    EAknNaviPaneEditorIndicatorQwertyShift,

    EAknNaviPaneEditorIndicatorArabicCase = 130,
    EAknNaviPaneEditorIndicatorHebrewCase,
    EAknNaviPaneEditorIndicatorArabicIndicNumberCase,

    // APAC
    EAknNaviPaneEditorIndicatorPinyin = 150,
    EAknNaviPaneEditorIndicatorZhuyin,
    EAknNaviPaneEditorIndicatorStroke, // Stroke editor indicator for simplified Chinese.

    EAknNaviPaneEditorIndicatorZhuyinFind,
    EAknNaviPaneEditorIndicatorStrokeFind,

    // THAI
    EAknNaviPaneEditorIndicatorThai = 170,


    EAknNaviPaneEditorIndicatorStrokeTrad,  // Stroke editor indicator for traditional Chinese.

    // Application indicators to editor indicator pane
    EAknNaviPaneEditorIndicatorAudioAttached = 200,
    EAknNaviPaneEditorIndicatorImageAttached,
    EAknNaviPaneEditorIndicatorObjects,
    EAknNaviPaneEditorIndicatorAttachment,
    EAknNaviPaneEditorIndicatorMessageLength,
    EAknNaviPaneEditorIndicatorMessageInfo,

    // Extra application indicators to editor indicator pane in small statuspane
    EAknNaviPaneEditorIndicatorWaitBar,
    EAknNaviPaneEditorIndicatorProgressBar,
    EAknNaviPaneEditorIndicatorSecuredConnection,
    EAknNaviPaneEditorIndicatorWmlWaitGlobe,
    EAknNaviPaneEditorIndicatorGprs,
    EAknNaviPaneEditorIndicatorFileSize,

    // Navi pane editor indicators for Japanese
    EAknNaviPaneEditorIndicatorJapaneseHiraganaKanji = 300, // Hiragana/Kanji
    EAknNaviPaneEditorIndicatorJapaneseHiragana,            // Hiragana
    EAknNaviPaneEditorIndicatorJapaneseFullKatakana,        // Full-width Katakana
    EAknNaviPaneEditorIndicatorJapaneseHalfKatakana,        // Half-width Katakana
    EAknNaviPaneEditorIndicatorJapaneseFullUpperAlphabet,   // Full-width Upper Case alphabet
    EAknNaviPaneEditorIndicatorJapaneseFullLowerAlphabet,   // Full-width Lower Case alphabet
    EAknNaviPaneEditorIndicatorJapaneseFullTextAlphabet,    // Full-width Text Case alphabet
    EAknNaviPaneEditorIndicatorJapaneseFullNumeric          // Full-width numeric
    };


enum  // Indicator states
    {
    EAknIndicatorStateOff,
    EAknIndicatorStateOn,
    EAknIndicatorStateAnimate
    };

enum // Signal indicator states
    {
    // GPRS indicator states
    EAknSignalGprsIndicatorOff = 0,
    EAknSignalGprsIndicatorAvailable,  // Same as EAknSignalGprsIndicatorOff
    EAknSignalGprsIndicatorAttached,
    EAknSignalGprsIndicatorEstablishingContext,
    EAknSignalGprsIndicatorContext,
    EAknSignalGprsIndicatorSuspended,
    EAknSignalGprsIndicatorMultipdp,

     // Common packet data indicator states
    EAknSignalCommonPacketDataIndicatorOff = 0x100,
    EAknSignalCommonPacketDataIndicatorAvailable,  // Same as EAknSignalCommonPacketDataIndicatorOff
    EAknSignalCommonPacketDataIndicatorAttached,
    EAknSignalCommonPacketDataIndicatorEstablishingContext,
    EAknSignalCommonPacketDataIndicatorContext,
    EAknSignalCommonPacketDataIndicatorSuspended,
    EAknSignalCommonPacketDataIndicatorMultipdp,

     // WCDMA indicator states
    EAknSignalWcdmaIndicatorOff = 0x200,
    EAknSignalWcdmaIndicatorAvailable,
    EAknSignalWcdmaIndicatorAttached,
    EAknSignalWcdmaIndicatorEstablishingContext,
    EAknSignalWcdmaIndicatorContext,
    EAknSignalWcdmaIndicatorMultipdp,
    EAknSignalWcdmaIndicatorSuspended,


    // CDMA indicator states
    EAknSignalCdmaIndicatorOff = 0x300,
    EAknSignalCdmaIndicatorNoService,
    EAknSignalCdmaIndicatorAvailable,
    EAknSignalCdmaIndicatorNotAvailable,
    EAknSignalCdmaIndicatorActive,
    EAknSignalCdmaIndicatorDormant,
    EAknSignalCdmaIndicatorSending,
    EAknSignalCdmaIndicatorReceiving
    };



// Grid layout flags






// Chooses right-to-left or left-to-right depending on language's writing direction
// You MUST use CurrentDataIndex() and CurrentItemIndex() from grid correctly if you
// choose this flag! (Most cases you want to use CurrentDataIndex(), not CurrentItemIndex!)









// Bitmap Animation flags





// Defining colors in resource file (this is for defining your own color schemes, do not use in applications!) (num is the number from LAF specification!) This is used in eikcolor.ra to setup color lists.



// This is used in eikcolor.ra



//
// defines for different listbox layouts
// gfx = index to the image in icon array in A column
// heading = heading text in B column
// text = main text for C column
// optgfx1 = index to optional image in D column
// optgfx2 = index to 2nd optional image in D column
//
// Example:  LB_SINGLE_GRAPHIC_HEADING(1, qgn_icon_1, qtn_text_1)







// SCT enumerations
enum  // ids in SCT_CHAR_SET resource.
    {
    EAknSCTLowerCase,
    EAknSCTUpperCase,
    EAknSCTNumeric,
    EAknSCTFullCase,
    EAknSCTHalfCase,
    EAknSCTChiChineseInputModes = EAknSCTUpperCase,
    EAknSCTChiLatinInputModes = EAknSCTLowerCase
    };

// For Setting Page resource so that no number is displayed


// Flag for Setting Item resource




enum TSCTQueryCtrlIds
    {
    EAknSCTQueryHeadingId = 1,
    EAknSCTQueryContentId
    };

// Enemerations for Avkon KeySounds

enum TAvkonSKeyRepeatType
    {
    ESKeyTypeShort,
    ESKeyTypeLong,
    ESKeyTypeRepeat
    };

// These SID numbers should specify all AVKON defined SID's
// The first item starts from 1000 so there are no clashes
// with application defined SID's (which should start at 0)
enum TAvkonSystemSID
    {
    EAvkonSIDNoSound = 1000,
    EAvkonSIDDefaultSound = 1001,
    EAvkonSIDStandardKeyClick = 1002,
    EAvkonSIDConfirmationTone = 1003,
    EAvkonSIDInformationTone = 1003,
    EAvkonSIDWarningTone = 1004,
    EAvkonSIDErrorTone = 1005,
    EAvkonSIDVolumeMaxTone = 1006,
    EAvkonSIDVolumeMinTone = 1007,
    EAvkonSIDReadialCompleteTone = 1008,
    EAvkonSIDBatteryLowTone = 1009,
    EAvkonSIDChargingBatteryTone  = 1010,
    EAvkonSIDConnectionStartTone  = 1011,
    EAvkonSIDConnectionStopTone  = 1012,
    EAvkonSIDOperationReadyTone  = 1013,
    EAvkonSIDNameDiallerStartTone  = 1014,
    EAvkonSIDNameDiallerErrorTone  = 1015,
    EAvkonSIDNameDiallerAbortTone  = 1016,
    EAvkonSIDPowerOffTone  = 1017,
    EAvkonSIDPowerOnTone  = 1018,
    EAvkonSIDRechargeBatteryTone = 1019,
    EAvkonSIDVoiceRecordingTone  = 1020,
    EAvkonSIDVoiceRecordingStartTone  = 1021,
    EAvkonSIDVoiceRecordingStopTone  = 1022,
    EAvkonSIDWrongCharger  = 1023,
    EAvkonSIDNetBusy = 1024,
    EAvkonSIDNetCallWaiting = 1025,
    EAvkonSIDNetReorder = 1026,
    EAvkonSIDNetCongestion = 1027,
    EAvkonSIDNetSpecialInformation = 1028,
    EAvkonSIDNetRadioNotAvailable = 1029,
    EAvkonSIDIHFActive = 1030,
    EAvkonSIDRadioPathAcknowledge = 1031,
    EAvkonSIDDial = 1032,
    EAvkonSIDRingGoing = 1033,
    EAvkonSIDLocationRequest = 1034
    };

// These are used as priority values for Media Server
enum TAvkonSoundsPriority
    {
    EAvkonKeyClickPriority = 45, // contains DTMF and camera
    EAvkonPoweringTonesPriority = 50,
    EAvkonLowLevelNotesPriority = 55,
    EAvkonConfirmationNotePriority = 55,
    EAvkonVolumeSettingTonesPriority = 60,
    EAvkonConnectionTonesPriority = 65,
    EAvkonHighLevelNotesPriority = 70,
    EAvkonErrorNotePriority = 70,
    EAvkonWarningNotePriority = 70,
    EAvkonVoiceDiallingTonesPriority = 73,
    EAvkonNetworkingTonesPriority = 75,
    EAvkonRecordingTonesPriority = 80,
    EAvkonChargingTonesPriority = 85,
    EAvkonNewMessageTonesPriority = 90,
    EAvkonAlarmTonesPriority = 95,
    EAvkonRingingTonesPriority = 100
    };

// These are used as priority preference values for Media Server
enum TAvkonSoundsPreference
    {
    EAknAudioPrefIncomingCall       =0x01340001,
    EAknAudioPrefIncomingCallLine2  =0x01330001,
    EAknAudioPrefIncomingDataCall       =0x01320001,
    EAknAudioPrefAutoRedialCompleted    =0x01310001,

    EAknAudioPrefAlarmClock         =0x01220001,
    EAknAudioPrefCalendarAlarm      =0x01210001,

// Message Preferences
    EAknAudioPrefNewSMS         =0x01120001,
    EAknAudioPrefNewSpecialMessage  =0x01110001,

// Battery preferences
    EAknAudioPrefBatteryLow         =0x01030001,
    EAknAudioPrefRechargeBattery        =0x01020001,
    EAknAudioPrefWrongCharger       =0x01010001,

// Recording Tone preferences
    EAknAudioPrefVoiceRecStart      =0x00930001,
    EAknAudioPrefVoiceRecRecording  =0x00920001,
    EAknAudioPrefVoiceRecStop       =0x00910001,

// Network preferences
    EAknAudioPrefRadioPathAck       =0x00890001,
    EAknAudioPrefDial               =0x00880001,
    EAknAudioPrefRingGoing          =0x00870001,
    EAknAudioPrefBusy               =0x00860001,
    EAknAudioPrefCallWaiting        =0x00850001,
    EAknAudioPrefReorder            =0x00840001,
    EAknAudioPrefCongestion         =0x00830001,
    EAknAudioPrefSpecialInformation =0x00820001,
    EAknAudioPrefRadioNotAvailable  =0x00810001,

// High level preferences
    EAknAudioPrefError      =0x00720001,
    EAknAudioPrefWarning        =0x00710001,

// Voice Dialling preferences
    EAknAudioPrefVoiceStarting  =0x00630001,
    EAknAudioPrefVoiceError     =0x00620001,
    EAknAudioPrefVoiceAbort     =0x00610001,

// Connection preferences
    EAknAudioPrefConnectionStart    =0x00530001,
    EAknAudioPrefConnectionStop =0x00520001,
    EAknAudioPrefOperationReady =0x00510001,

// Volume / IHF preferences /Previews
    EAknAudioPrefFilePreview    =0x00440001,
    EAknAudioPrefAudioVolumeMin =0x00430001,
    EAknAudioPrefAudioVolumeMax =0x00420001,
    EAknAudioPrefIHFActive      =0x00410001,

// Low Level preferences
    EAknAudioPrefCharging       =0x00330001,
    EAknAudioPrefConfirmation   =0x00320001,
    EAknAudioPrefDefaultTone    =0x00310001,

// Phone power preferences
    EAknAudioPrefPowerOn        =0x00220001,
    EAknAudioPrefPowerOff       =0x00210001,

// Key press / camera click preferences
    EAknAudioPrefKeyPressNonDTMF    =0x00140001,
    EAknAudioPrefKeyDownDTMF    =0x00130001,
    EAknAudioPrefKeyUpDTMF      =0x00120001,
    EAknAudioPrefCamera     =0x00110001,

// Record and VoCos Preferences
    EAknAudioPrefVoiceRec       =0x00060001,
    EAknAudioPrefComposer       =0x00050001,
    EAknAudioPrefRingFilePreview    =0x00040001,
    EAknAudioPrefVocosPlayback  =0x00030001,
    EAknAudioPrefVocosTrain     =0x00020001,
    EAknAudioPrefVocosRecog     =0x00010001,

    EAvkonKeyClickPreference = 0x00140001,
    EAvkonConfirmationNotePreference = 0x00320001,
    EAvkonErrorNotePreference = 0x00720001,
    EAvkonWarningNotePreference = 0x00710001
    };

// Constants for integer editor widths; may be required in resource


enum TMessageQueryCtrlIds
    {
    EAknMessageQueryHeaderId = 1,
    EAknMessageQueryContentId
    };

// CAknIncallBubble flags
    /**
    *   Bit             Explanation
    *   0 and 1         Call state
    *   2               No Ciphering
    *   3               Is muted
    *   4               Is Visible
    *   5               Is a Fax
    *   6               Is a Data call
    *   7               Is a Hscsd data call
    *   8               Line 2 indication
    *   9               Is a Video call
    *   10              Is an emergency call
    */
enum TAvkonIncallStatusBubbleFlags
    {
    EAknStatusBubbleAlerting     = 0x00, //  One of
    EAknStatusBubbleActive       = 0x01, //  these
    EAknStatusBubbleOnHold       = 0x02, //  to set
    EAknStatusBubbleDisconnected = 0x03, //  the call state
    EAknStatusBubbleNoCiphering  = 0x04,
    EAknStatusBubbleMuted        = 0x08,
    EAknStatusBubbleVisible      = 0x10,
    EAknStatusBubbleFax      = 0x20,
    EAknStatusBubbleData      = 0x40,
    EAknStatusBubbleDataHscsd      = 0x80,
    EAknStatusBubbleLine2      = 0x100,
    EAknStatusBubbleVideo      = 0x200,
    EAknStatusBubbleEmergency  = 0x400
    };


/**
 * Timeouts for note dialog wrappers
 * These should be kept same as CAknNoteDialog::TTimeout.
 */
enum TAknNoteDialogTimeout
    {
    EAknNoteDialogUndefinedTimeout = 0,
    EAknNoteDialogShortTimeout = 1500000,
    EAknNoteDialogLongTimeout = 3000000,

    // Change these if Notes UI spec changes:
    EAknConfirmationNoteTimeout = EAknNoteDialogShortTimeout,
    EAknInformationNoteTimeout = EAknNoteDialogLongTimeout,
    EAknErrorNoteTimeout = EAknNoteDialogLongTimeout,
    EAknWarningNoteTimeout = EAknNoteDialogLongTimeout
    };

/**
 * Tones for note dialog wrappers
 * These should be kept same as CAknNoteDialog::TTone.
 */
enum TAknNoteDialogTone
    {
    EAknNoteDialogNoTone = 0,
    EAknNoteDialogConfirmationTone = EAvkonSIDConfirmationTone,
    EAknNoteDialogWarningTone = EAvkonSIDWarningTone,
    EAknNoteDialogErrorTone  = EAvkonSIDErrorTone
    };


enum TAknSelectionListDialogFlags
    {
    EAknFlagFind = 0x0001
    };

enum TAknIconArrayType
    {
    EAknIconArrayNone,
    EAknIconArraySimple,
    EAknIconArrayComplex
    };

// This enum is to distinguish at runtime whether you are in
// European or APAC build variant.
enum EVariantFlag
   {
   EEuropeanVariant=0,
   EApacVariant
   };

//
// This can be extended for additional subvariants.  Routine in AknUtils should be updated
// to return the correct sub-variant.
//
//
enum ESubVariantFlag
   {
   ENoSubVariant = 0,
   EPrcSubVariant,
   EHongKongSubVariant,
   ETaiwanSubVariant
   };


// This is the max length of the screensaver text


// These flags are to be used in conjunction with CAknForm



//
// Deprecated






enum TAknKeyBlockMode
    {
    EDefaultBlockMode=0,
    ENoKeyBlock
    };

// Separator line.
enum TAknSeparatorLinePosition
    {
    ENoLine,
    EAColumn,
    EABColumn,
    EBCColumn
    };
enum TAknColourSelectionDialogIds {
    ECtrlGridType = 100,
    EColourGridPopup,
    EColourGridPopupNone
};


// custom text cursor constants

enum TAknCustomTextCursorIds
    {
    KAknCustomTextCursorIdLeftToRight = 0x101fdf03,
    KAknCustomTextCursorIdRightToLeft = 0x101fdf04,
    KAknCustomTextCursorIdLeftToRightThin = 0x101fe51c,
    KAknCustomTextCursorIdRightToLeftThin = 0x101fe51d
    };

enum TAknNaviPaneBackgroundTypes
    {
    EAknNaviPaneBackgroundTypeNotDefined  = 0,
    EAknNaviPaneBackgroundTypeWipe        = 1,
    EAknNaviPaneBackgroundTypeSolid       = 2
    };
// common bitmap file definitions (for .rss etc.)







// End key closing event. If this window server event is received,
// by default application will be closed unless it is system application.






# 22 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\avkon.rh" 2




STRUCT NAVI_DECORATOR
	{
	WORD type=ENaviDecoratorControlNone;
	STRUCT control;
	}

STRUCT TITLE_PANE
	{
	LTEXT txt="";
	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	}

STRUCT CONTEXT_PANE
	{
	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	}

STRUCT TAB_GROUP
	{
	WORD tab_width = EAknTabWidthWithTwoTabs;  // two tabs
	WORD active = 0; // index of the first active tab
	STRUCT tabs[];
	}

STRUCT TAB
	{
	WORD id=0;
	LTEXT txt="";
	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	}

STRUCT NAVI_LABEL
	{
	LTEXT txt="";
	}

STRUCT NAVI_IMAGE
	{
   	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	}

STRUCT SIGNAL_PANE
	{
	WORD level = 0;
	}

STRUCT BATTERY_PANE
	{
	WORD level = 0;
	}

STRUCT INDICATOR_PANE
	{
	STRUCT indicators[];
	}

STRUCT INDICATOR
	{
	WORD uid;
	WORD npriority=0xffff;
	WORD wpriority=0xffff;
   	LTEXT bmpfile="";
	STRUCT states[];
	}

STRUCT INDICATOR_STATE
	{
	WORD id;
	STRUCT icons[];
	}

STRUCT INDICATOR_ICON
	{
	WORD narrowbmpid=0xffff;
	WORD narrowbmpmask=0xffff;
	WORD widebmpid=0xffff;
	WORD widebmpmask=0xffff;
	}

STRUCT AVKON_VIEW
	{
	LLINK hotkeys=0;
	LLINK menubar=0;
	LLINK cba=0;
	}

STRUCT AVKON_NOTE
	{
	WORD layout;
	LTEXT singular_label;
	LTEXT plural_label="";
	LTEXT imagefile="";
	WORD imageid=0xffff;
	WORD imagemask=0xffff;
	LTEXT iconfile="";
	WORD iconid=0xffff;
	WORD iconmask=0xffff;
	LLINK animation=0;
	WORD flags=0; //TNoteFlags (defined in aknnoteattributes.h)
	}

STRUCT NOTE_COMPONENT
	{
	WORD component_type;
	WORD x;
	WORD y;
	WORD width;
	WORD height;
	}

STRUCT NOTE
	{
	STRUCT components[];
	}

STRUCT AVKON_CONFIRMATION_QUERY
	{
	WORD layout;
	LTEXT label;
	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	LLINK animation=0; 
	}

STRUCT AVKON_DATA_QUERY
	{
	WORD layout;
	LTEXT label;
	STRUCT control;
	}

STRUCT AVKON_MESSAGE_QUERY
    {
    LTEXT message = "";
    }

STRUCT AVKON_MULTI_LINE_DATA_QUERY
	{
	WORD layout;   
	LTEXT firstlabel;
	LLINK firstcontrol;
	LTEXT secondlabel;
	LLINK secondcontrol;
	}


// use this with CAknQueryDialog.
// This is for one dialog DLG line with EAknCtListQueryControl
//
// The list query window type is determined from EAknCtSinglePopupMenuListBox - if you want to
// have your own borders, derive from CAknListQueryDialog and override some methods.

STRUCT AVKON_LIST_QUERY_CONTROL
	{
	WORD listtype; // type of the list, for example EAknCtSinglePopupMenuListBox (window type is determined from this)
	STRUCT listbox; // LISTBOX resource, use AVKON_LIST_QUERY_LIST or AVKON_MULTISELECTION_LIST_QUERY_LIST
	LTEXT heading = "";
	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	LLINK animation=0;
	}

STRUCT AVKON_HEADING
	{
	LTEXT label = "";  // default is no heading
	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	LLINK animation=0;
	LLINK headinglayout = 0x8cc00ca ;
	}

// CAknPopupField
STRUCT POPUP_FIELD
	{
	WORD flags=0; // permitted flags: EAknPopupFieldFlagAllowsUserDefinedEntry
	WORD width=0; // in characters
	LTEXT other=""; // if non-empty, replaces 
	LLINK emptynote = 0; // note to be displayed if popupfield is empty
	LTEXT empty=""; // text to display if popupfield is empty
	LTEXT invalid = ""; // text to display if popupfield is invalid
	}

STRUCT POPUP_FIELD_TEXT
	{
	STRUCT popupfield; // only use POPUP_FIELD here
	LLINK textarray = 0; // resource ID of an array of text
	WORD active = 0; // zero based, item in textarray to be initially selected
	}

STRUCT POPUP_FIELD_SELECTION_BMP
	{
	LTEXT bmpfile="";
	WORD bmpidon=0xffff;
	WORD bmpmaskon=0xffff;
	WORD bmpidoff=0xffff;
	WORD bmpmaskoff=0xffff;
	}

STRUCT SLIDER
	{
	WORD layout;
	WORD minvalue;
	WORD maxvalue;
	WORD step;
	WORD valuetype=EAknSliderValueBareFigure;
	WORD decimalplaces=0;
	LTEXT singular_valuelabel = "";
	LTEXT minlabel="";
	LTEXT maxlabel="";
	LTEXT valuelabel="";
    LLINK graphical_image=0;
	}

STRUCT VOLUME
	{
	WORD flags;
	WORD value;
	LTEXT bmpfile="";
	WORD bmpid=0xffff;
	WORD bmpmask=0xffff;
	}

STRUCT NUMSECRETED
	{
 	WORD num_code_chars=8;
	}

STRUCT GRID_STYLE
	{
	WORD layoutflags = 0;
	WORD primaryscroll = 0;
	WORD secondaryscroll = 0;
	WORD itemsinprimaryorient = 0;
	WORD itemsinsecondaryorient = 0;
	WORD height = 0;
	WORD width = 0;
	WORD gapwidth = 0;
	WORD gapheight = 0;
	}

STRUCT GRID
	{
	BYTE version = 0;
	WORD flags = 0;
	WORD height = 5;		// in items
	WORD width = 10;		// in chars
	LLINK array_id = 0;
	LTEXT emptytext = "";
	LLINK style = 0; 
	}

STRUCT AVKON_SETTING_PAGE
	{
	WORD number = (-16380) ;
	LTEXT label;
	LTEXT hint_text;
	LLINK softkey_resource = 0;
	LLINK menubar= 0;
	WORD type=0xffff;
	LLINK editor_resource_id = 0;
	LLINK invalid_contents_softkey_resource = 0;
	LLINK extension = 0;
	}

STRUCT AVKON_SETTING_ITEM_LIST
	{
	WORD flags = 0; // Allowed values: EAknSettingItemListNumberedStyle 
	LTEXT title = "";
	WORD initial_number = 1;
	STRUCT items[];
	}


STRUCT AVKON_SETTING_ITEM
	{
	WORD identifier = 0;
	LTEXT name ="";
	LLINK setting_page_resource = 0;
	WORD type=0xffff;  
	LLINK setting_editor_resource = 0;
	LLINK associated_resource = 0;
	LTEXT empty_item_text = "";
	LTEXT compulsory_ind_string = "";
	LLINK reserved = 0;  // Added for extensions
	}

STRUCT AVKON_PASSWORD_CONFIRMATION
	{
	LLINK password_query_resource = 0;
	LLINK success_note_resource = 0;
	LLINK failure_note_resource = 0;
	}

STRUCT AVKON_ENUMERATED_TEXT
	{
	WORD value = 0 ;
	LTEXT text;
	}

STRUCT AVKON_POPUP_SETTING_TEXTS
	{
	WORD flags = 0;
	LLINK setting_texts_resource = 0;
	LLINK popped_up_texts_resource = 0;
	LLINK reserved = 0;
	}

STRUCT AVKON_SEARCH_FIELD
	{
	}

STRUCT AVKON_LISTBOX_LINES
	{
	STRUCT vline1;
	STRUCT vline2;
	STRUCT hline;
	}

// Bitmap Animation
STRUCT BMPANIM_DATA
	{
	WORD frameinterval	= -1;
	WORD playmode		= 0;
	BYTE flash		= 0;
	LTEXT bmpfile		= "";
	LLINK frames		= 0;
	LLINK backgroundframe	= 0;
 	}

STRUCT BMPANIM_FRAME
	{
	WORD time		= -1;
	WORD posx		= 0;
	WORD posy		= 0;
	WORD bmpid		= -1;
	WORD maskid		= -1;
	}



// Resource-based layout resources (Deprecated)
// These does not define absolute coordinates => resizing these layouts is possible!
//
// (those which does not mention column or form in their name could be used later by
// other controls for their layout - there will be generic resource reader for these)

// this is used with listboxes
STRUCT AVKON_LB_LAYOUT_POS
	{
	WORD l= (-16380) ; 
	WORD t= (-16380) ; 
	WORD r= (-16380) ; 
	WORD b= (-16380) ; 
	WORD W= (-16380) ; 
	WORD H= (-16380) ;
	}

// this is used with listboxes too
STRUCT AVKON_LB_LAYOUT_GFX
	{
	WORD id;
	WORD C= (-16380) ;
	WORD l= (-16380) ;
	WORD t= (-16380) ;
	WORD r= (-16380) ;
	WORD b= (-16380) ;
	WORD W= (-16380) ;
	WORD H= (-16380) ;
	}

// This is used with listboxes
STRUCT AVKON_LB_LAYOUT_TEXT
	{
	WORD id;
	WORD font; WORD C; WORD lm; WORD rm;  WORD B; WORD W; WORD align;
	}

// This is used with CAknLayoutUtils::LayoutControl()
STRUCT AVKON_LAYOUT_CONTROL
	{
	WORD C= (-16380) ;
	WORD l= (-16380) ;
	WORD t= (-16380) ;
	WORD r= (-16380) ;
	WORD b= (-16380) ;
	WORD W= (-16380) ;
	WORD H= (-16380) ;
	}

// This is used with TAknLayoutRect
STRUCT AVKON_LAYOUT_RECT
	{
	WORD C= (-16380) ;
	WORD l= (-16380) ;
	WORD t= (-16380) ;
	WORD r= (-16380) ;
	WORD b= (-16380) ;
	WORD W= (-16380) ;
	WORD H= (-16380) ;
	}

// this is used with AknListBoxLayouts::LayoutImage


STRUCT AVKON_LAYOUT_TEXT
	{
	WORD font;
	WORD C;
	WORD l;
	WORD r;
	WORD B;
	WORD W;
	WORD J;
	}

// This should be used with CAknLayoutUtils::LayoutEdwin
STRUCT AVKON_LAYOUT_EDWIN
	{
	WORD font;
	WORD C;
	WORD l;
	WORD r;
	WORD B;
	WORD W;
	WORD J;
	WORD lines=1;   // Number of lines shown
	WORD nextB=0;   // Second row's baseline position
	}

// This can be used with CAknLayoutUtils::LayoutLabel to layout CEikLabel's.
STRUCT AVKON_LAYOUT_LABEL
	{
	WORD font;
	WORD C;
	WORD l;
	WORD r;
	WORD B;
	WORD W;
	WORD J;
	WORD nextB=0;
	}

// This is used with CAknLayoutUtils::LayoutPopupField()
STRUCT AVKON_LAYOUT_FORM_FIELD_POPUP_PANE
	{
	WORD font;
	WORD C = (-16380) ;
	WORD l = (-16380) ;
	WORD t = (-16380) ;
	WORD r = (-16380) ;
	WORD b = (-16380) ;
	WORD W = (-16380) ;
	WORD H1 = (-16380) ;
	WORD H2 = (-16380) ;
	WORD H3 = (-16380) ;
	WORD H4 = (-16380) ;
	WORD H5 = (-16380) ;
	WORD H6 = (-16380) ;
	WORD lines = 1;   // Number of lines shown
	}

STRUCT AVKON_LB_LAYOUT_AREA
	{
	WORD id;
	WORD x1; WORD y1;
	WORD x2; WORD y2;
	}

STRUCT AVKON_LB_LAYOUT_COMMAND
	{
	WORD id;
	WORD cmd;
	WORD data=0;	
	}

// This is only for listboxes, use 
// AknLayoutUtils/TAknLayoutText/TAknLayoutRect for getting correct layouts.
STRUCT AVKON_LAYOUT_MANAGER
	{
	STRUCT gfx[];  // AVKON_LAYOUT_GFX
	STRUCT text[]; // AVKON_LAYOUT_TEXT
	STRUCT cmds[]; // AVKON_LAYOUT_COMMAND
	STRUCT area[]; // AVKON_LAYOUT_AREA
	STRUCT pos;     // AVKON_LAYOUT_POS
	}

// This should be used with AknEditUtils::ConstructEditingL
STRUCT AVKON_CONFIG_EDWIN
	{
	WORD editingSpace;	  // Max number of character in a editor field
	WORD editingWindow;   // Maximum number of lines in a editor field
	WORD characterCase;   // EAknEditorCharactersUpperCase,	EAknEditorCharactersLowerCase, EAknEditorCharactersTextCase
	WORD justification;   // EAknEditorAlignNone, EAknEditorAlignCenter, EAknEditorAlignLeft, EAknEditorAlignRight
	WORD allowedToMoveInsertionPoint; 
	WORD cursorYesNo;
	WORD overflowYesNo;
	}


STRUCT AVKON_CBA_BUTTON
	{
	BYTE version= 10 ;
	WORD id=0;
	WORD longpressid=0;
   	LTEXT txt="";
	LTEXT bmpfile="";
  	WORD bmpid=0xffff;		// -1
	WORD bmpmask=0xffff;	// -1
	}
// Special Character Table

STRUCT SPECIAL_CHAR_TABLE
	{
	STRUCT contents[]; // SCT_CHAR_SET
	}


STRUCT SCT_CHAR_SET
	{
	WORD id;
	LTEXT chars = "";
	}



// ---------------------------------------------------------
// Resource structure for CAknIconArray class.
// ---------------------------------------------------------
//
STRUCT AKN_ICON_ARRAY
	{
	WORD type = EAknIconArraySimple;
	// Bitmap file name
	LTEXT bmpfile;
	// Array of AKN_ICON structures.
	STRUCT icons[];
	}

STRUCT AKN_ICON_ARRAY_ARRAY
	{
	WORD type = EAknIconArrayComplex;
	STRUCT iconarrays[]; // AKN_ICON_ARRAY
	}


// ---------------------------------------------------------
// One icon in AKN_ICON_ARRAY
// ---------------------------------------------------------
//
STRUCT AKN_ICON
	{
	// Id of the icon bitmap
	LONG iconId;
	// Id of the mask bitmap
	LONG maskId;
	}

// Avkon KeySounds


STRUCT AVKON_SOUND_INFO
	{
	WORD signature1 = 0x1234;
	WORD signature2 = 0x5678;
	WORD sid;
	WORD priority = EAvkonKeyClickPriority;
	LONG preference = EAvkonKeyClickPreference;
	LTEXT file="";
	WORD frequency=0;
	LONG ms=0;
	WORD sequencelength=0;
	BYTE sequence[];
	BYTE volume=9; // default to loudest value
	}

STRUCT AVKON_SOUND_INFO_LIST 
	{
	STRUCT list[];
	}

STRUCT AVKON_SKEY_INFO
	{
	WORD sid = EAvkonSIDDefaultSound;
	WORD key;
	BYTE type = ESKeyTypeShort;
	}

STRUCT AVKON_SKEY_LIST
	{
	STRUCT list[];
	}

STRUCT PHONE_NUMBER_EDITOR
	{
	WORD maxChars=30;
	WORD maxLines;
	LTEXT truncation="";
	STRUCT formats[];
	}

STRUCT PHONE_NUMBER_EDITOR_FORMAT
	{
	WORD top;
	WORD left;
	WORD bottom;
	WORD right;
	LONG border=0;
	WORD lines;
	WORD bottomBaselineOffset;
	WORD baselineSeparation;
	WORD font;
	}

// CAknPopupSettingList
STRUCT POPUP_SETTING_LIST
	{
	WORD flags; // permitted flags: EAknPopupSettingListFlagAllowsUserDefinedEntry
	WORD width; // in characters.
	LTEXT other="Other ...";
	LTEXT empty_text="No options";
	LLINK new_item_setting_page_resource = 0; // These 3 to allow setting page launch from list pane
	WORD type=0xffff;				
	LLINK new_item_setting_editor_resource = 0;
	}

// This comes from DIALOG resource and must be updates accordingly when
// DIALOG resource is changed. see eikon.rh
STRUCT AVKON_LIST_QUERY
    {
    LONG flags = ((0x001 | 0x200  | 0x040  | 0x2000 ) ) ;
    LTEXT xxxx1 = "";
    LLINK xxxx2 = 0;
    LLINK softkeys = 0x8cc0014 ; // CBA
    STRUCT items[]; // AVKON_LIST_QUERY_DLG_LINE
    LLINK xxxx3 = 0;
    }

STRUCT AVKON_MULTISELECTION_LIST_QUERY
    {
    LONG flags = ((0x001 | 0x200  | 0x040  | 0x2000 ) ) ;
    LTEXT xxxx1 = "";
    LLINK xxxx2 = 0;
    LLINK softkeys = 0x8cc0014 ; // CBA
    STRUCT items[]; // AVKON_MULTISELECTION_LIST_QUERY_DLG_LINE
    LLINK xxxx3 = 0;
    }

STRUCT AVKON_LIST_QUERY_DLG_LINE
    {
    WORD type = EAknCtListQueryControl;
    LTEXT prompt = "";
    WORD id = EListQueryControl;
    LONG itemflags = 0;
    STRUCT control; // AVKON_LIST_QUERY_CONTROL
    LTEXT trailer = "";
    LTEXT bmpfile = "";
    WORD bmpid = 0xffff;
    WORD bmpmask = 0xffff;
    LTEXT tooltip = "";
    }

STRUCT AVKON_MULTISELECTION_LIST_QUERY_DLG_LINE
    {
    WORD type = EAknCtListQueryControl;
    LTEXT prompt = "";
    WORD id = EListQueryControl;
    LONG itemflags = 0;
    STRUCT control; // AVKON_LIST_QUERY_CONTROL
    LTEXT trailer = "";
    LTEXT bmpfile = "";
    WORD bmpid = 0xffff;
    WORD bmpmask = 0xffff;
    LTEXT tooltip = "";
    }


STRUCT AVKON_LIST_QUERY_LIST
    {
    BYTE version = 0;
    WORD flags = ((0x0080 ) ) ;
    WORD height = 5;
    WORD width = 10;
    LLINK array_id = 0;
    }

STRUCT AVKON_MULTISELECTION_LIST_QUERY_LIST
    {
    BYTE version = 0;
    WORD flags = ((0x0080 )  | 0x0001   | 0x2000 ) ;
    WORD height = 5;
    WORD width = 10;
    LLINK array_id = 0;    
    }

// LISTBOX resources:
STRUCT AVKON_SELECTION_LIST
    {
    BYTE version = 0;
    WORD flags = ((0x0080 ) ) ;
    WORD height = 5;
    WORD width = 10;
    LLINK array_id = 0;
    }
STRUCT AVKON_MARKABLE_LIST
    {
    BYTE version = 0;
    WORD flags = ((0x0080 )  | 0x0001   | 0x4000 ) ;
    WORD height = 5;
    WORD width = 10;
    LLINK array_id = 0;
    }

STRUCT AVKON_MULTISELECTION_LIST
    {
    BYTE version = 0;
    WORD flags = ((0x0080 )  | 0x0001   | 0x2000 ) ;
    WORD height = 5;
    WORD width = 10;
    LLINK array_id = 0;
    }

STRUCT AVKON_MENU_LIST
    {
    BYTE version = 0;
    WORD flags = ((0x0080 ) ) ;
    WORD height = 5;
    WORD width = 10;
    LLINK array_id = 0;
    }

STRUCT AVKON_INTEGER_EDWIN
	{
    WORD maxlength = 0;
	LONG min =			 -99999999;
	LONG max =			  99999999;
	LONG unset_value=	-100000000;
	LLINK extension1 = 0;
	LLINK extension2 = 0;
	}



// Avkon note wrappers


STRUCT AKN_NOTE_WRAPPER
    {
    // Id of the dialog resource for this note
    LLINK resId;
    // see TAknNoteDialogTimeout
    LONG timeout;
    // see TAknNoteDialogTone
    WORD  tone=-1;
    // Prompt text
    LTEXT text="";
    }

STRUCT AVKON_GROUPED_NOTE_TEXTS
  {
  LLINK singular_label; // must point to resource of type TBUF 
  LLINK plural_label; // must point to resource of type TBUF 
  WORD flags=0; // for future proofing
  }



// DEPRECATED.
STRUCT AKN_SELECTION_LIST
    {
    WORD flags = 0; // see avkon.hrh / EAknFlagFind etc..
    WORD listbox = EAknCtSingleListBox; // listbox layout 
    LLINK menubar = 0; // MENUBAR resource 
    LLINK dialogresource = 0x8cc0099 ;
    }

STRUCT AVKON_UNUSED
	{
	}

# 20 "C:\\KG\\LESSA\\Symbian\\data\\LESSA.rss" 2

# 1 "C:\\Symbian\\8.1a\\S60_2nd_FP3\\\\epoc32\\include\\avkon.mbg" 1
// AVKON.mbg
// Generated by BitmapCompiler
// Copyright (c) 1998-2001 Symbian Ltd.  All rights reserved.
//

enum TMbmAvkon
	{
	EMbmAvkonQgn_graf_tab_21,
	EMbmAvkonQgn_graf_tab_21_mask,
	EMbmAvkonQgn_graf_tab_22,
	EMbmAvkonQgn_graf_tab_22_mask,
	EMbmAvkonQgn_graf_tab_31,
	EMbmAvkonQgn_graf_tab_31_mask,
	EMbmAvkonQgn_graf_tab_32,
	EMbmAvkonQgn_graf_tab_32_mask,
	EMbmAvkonQgn_graf_tab_33,
	EMbmAvkonQgn_graf_tab_33_mask,
	EMbmAvkonQgn_graf_tab_41,
	EMbmAvkonQgn_graf_tab_41_mask,
	EMbmAvkonQgn_graf_tab_42,
	EMbmAvkonQgn_graf_tab_42_mask,
	EMbmAvkonQgn_graf_tab_43,
	EMbmAvkonQgn_graf_tab_43_mask,
	EMbmAvkonQgn_graf_tab_44,
	EMbmAvkonQgn_graf_tab_44_mask,
	EMbmAvkonQgn_graf_tab_long_21,
	EMbmAvkonQgn_graf_tab_long_21_mask,
	EMbmAvkonQgn_graf_tab_long_22,
	EMbmAvkonQgn_graf_tab_long_22_mask,
	EMbmAvkonQgn_graf_tab_long_31,
	EMbmAvkonQgn_graf_tab_long_31_mask,
	EMbmAvkonQgn_graf_tab_long_32,
	EMbmAvkonQgn_graf_tab_long_32_mask,
	EMbmAvkonQgn_graf_tab_long_33,
	EMbmAvkonQgn_graf_tab_long_33_mask,
	EMbmAvkonQgn_prop_signal_icon,
	EMbmAvkonQgn_prop_signal_icon_mask,
	EMbmAvkonQgn_indi_signal_gprs_attach,
	EMbmAvkonQgn_indi_signal_gprs_attach_mask,
	EMbmAvkonQgn_indi_signal_gprs_context,
	EMbmAvkonQgn_indi_signal_gprs_context_mask,
	EMbmAvkonQgn_indi_signal_gprs_suspended,
	EMbmAvkonQgn_indi_signal_gprs_suspended_mask,
	EMbmAvkonQgn_indi_signal_strength,
	EMbmAvkonQgn_indi_signal_strength_mask,
	EMbmAvkonQgn_indi_battery_strength,
	EMbmAvkonQgn_indi_battery_strength_mask,
	EMbmAvkonQgn_prop_battery_icon,
	EMbmAvkonQgn_prop_battery_icon_mask,
	EMbmAvkonQgn_indi_navi_arrow_left,
	EMbmAvkonQgn_indi_navi_arrow_left_mask,
	EMbmAvkonQgn_indi_navi_arrow_right,
	EMbmAvkonQgn_indi_navi_arrow_right_mask,
	EMbmAvkonQgn_stat_case_capital,
	EMbmAvkonQgn_stat_case_capital_mask,
	EMbmAvkonQgn_stat_case_small,
	EMbmAvkonQgn_stat_case_small_mask,
	EMbmAvkonQgn_stat_case_text,
	EMbmAvkonQgn_stat_case_text_mask,
	EMbmAvkonQgn_stat_case_title,
	EMbmAvkonQgn_stat_case_title_mask,
	EMbmAvkonQgn_stat_case_numeric,
	EMbmAvkonQgn_stat_case_numeric_mask,
	EMbmAvkonQgn_stat_query,
	EMbmAvkonQgn_stat_query_mask,
	EMbmAvkonQgn_stat_t9,
	EMbmAvkonQgn_stat_t9_mask,
	EMbmAvkonQgn_stat_case_capital_query,
	EMbmAvkonQgn_stat_case_capital_query_mask,
	EMbmAvkonQgn_stat_case_small_query,
	EMbmAvkonQgn_stat_case_small_query_mask,
	EMbmAvkonQgn_stat_case_text_query,
	EMbmAvkonQgn_stat_case_text_query_mask,
	EMbmAvkonQgn_stat_case_title_query,
	EMbmAvkonQgn_stat_case_title_query_mask,
	EMbmAvkonQgn_stat_case_numeric_query,
	EMbmAvkonQgn_stat_case_numeric_query_mask,
	EMbmAvkonQgn_stat_query_query,
	EMbmAvkonQgn_stat_query_query_mask,
	EMbmAvkonQgn_stat_t9_query,
	EMbmAvkonQgn_stat_t9_query_mask,
	EMbmAvkonQgn_indi_find_glass,
	EMbmAvkonQgn_indi_find_glass_mask,
	EMbmAvkonQgn_indi_find_glass_pinb,
	EMbmAvkonQgn_indi_find_glass_pinb_mask,
	EMbmAvkonQgn_indi_slider_edit,
	EMbmAvkonQgn_indi_slider_edit_mask,
	EMbmAvkonQgn_indi_slider_set,
	EMbmAvkonQgn_indi_slider_set_mask,
	EMbmAvkonQgn_indi_radiobutt_on,
	EMbmAvkonQgn_indi_radiobutt_on_mask,
	EMbmAvkonQgn_indi_radiobutt_off,
	EMbmAvkonQgn_indi_radiobutt_off_mask,
	EMbmAvkonQgn_indi_checkbox_on,
	EMbmAvkonQgn_indi_checkbox_on_mask,
	EMbmAvkonQgn_indi_checkbox_off,
	EMbmAvkonQgn_indi_checkbox_off_mask,
	EMbmAvkonQgn_indi_alarm_add,
	EMbmAvkonQgn_indi_alarm_add_mask,
	EMbmAvkonQgn_indi_marked_add,
	EMbmAvkonQgn_indi_marked_add_mask,
	EMbmAvkonQgn_indi_marked_grid_add,
	EMbmAvkonQgn_indi_marked_grid_add_mask,
	EMbmAvkonQgn_indi_level_back,
	EMbmAvkonQgn_indi_level_back_mask,
	EMbmAvkonQgn_indi_speaker_active,
	EMbmAvkonQgn_indi_speaker_active_mask,
	EMbmAvkonQgn_indi_speaker_passive,
	EMbmAvkonQgn_indi_speaker_passive_mask,
	EMbmAvkonQgn_indi_mic,
	EMbmAvkonQgn_indi_mic_mask,
	EMbmAvkonQgn_indi_earpiece_active,
	EMbmAvkonQgn_indi_earpiece_active_mask,
	EMbmAvkonQgn_indi_earpiece_passive,
	EMbmAvkonQgn_indi_earpiece_passive_mask,
	EMbmAvkonQgn_indi_attach_audio,
	EMbmAvkonQgn_indi_attach_audio_mask,
	EMbmAvkonQgn_indi_attach_image,
	EMbmAvkonQgn_indi_attach_image_mask,
	EMbmAvkonQgn_indi_object_gene,
	EMbmAvkonQgn_indi_object_gene_mask,
	EMbmAvkonQgn_indi_attach_gene,
	EMbmAvkonQgn_indi_attach_gene_mask,
	EMbmAvkonQgn_indi_bt_paired_add,
	EMbmAvkonQgn_indi_bt_paired_add_mask,
	EMbmAvkonQgn_indi_bt_trusted_add,
	EMbmAvkonQgn_indi_bt_trusted_add_mask,
	EMbmAvkonQgn_prop_checkbox_on,
	EMbmAvkonQgn_prop_checkbox_on_mask,
	EMbmAvkonQgn_prop_checkbox_off,
	EMbmAvkonQgn_prop_checkbox_off_mask,
	EMbmAvkonQgn_prop_radiobutt_on,
	EMbmAvkonQgn_prop_radiobutt_on_mask,
	EMbmAvkonQgn_prop_radiobutt_off,
	EMbmAvkonQgn_prop_radiobutt_off_mask,
	EMbmAvkonQgn_prop_group_small,
	EMbmAvkonQgn_prop_group_small_mask,
	EMbmAvkonQgn_prop_group_medium,
	EMbmAvkonQgn_prop_group_medium_mask,
	EMbmAvkonQgn_prop_group_large,
	EMbmAvkonQgn_prop_group_large_mask,
	EMbmAvkonQgn_prop_folder_small,
	EMbmAvkonQgn_prop_folder_small_mask,
	EMbmAvkonQgn_prop_folder_medium,
	EMbmAvkonQgn_prop_folder_medium_mask,
	EMbmAvkonQgn_prop_folder_large,
	EMbmAvkonQgn_prop_folder_large_mask,
	EMbmAvkonQgn_prop_folder_small_new,
	EMbmAvkonQgn_prop_folder_small_new_mask,
	EMbmAvkonQgn_prop_folder_temp,
	EMbmAvkonQgn_prop_folder_temp_mask,
	EMbmAvkonQgn_prop_nrtyp_address,
	EMbmAvkonQgn_prop_nrtyp_address_mask,
	EMbmAvkonQgn_prop_nrtyp_email,
	EMbmAvkonQgn_prop_nrtyp_email_mask,
	EMbmAvkonQgn_prop_nrtyp_fax,
	EMbmAvkonQgn_prop_nrtyp_fax_mask,
	EMbmAvkonQgn_prop_nrtyp_home,
	EMbmAvkonQgn_prop_nrtyp_home_mask,
	EMbmAvkonQgn_prop_nrtyp_mobile,
	EMbmAvkonQgn_prop_nrtyp_mobile_mask,
	EMbmAvkonQgn_prop_nrtyp_note,
	EMbmAvkonQgn_prop_nrtyp_note_mask,
	EMbmAvkonQgn_prop_nrtyp_pager,
	EMbmAvkonQgn_prop_nrtyp_pager_mask,
	EMbmAvkonQgn_prop_nrtyp_phone,
	EMbmAvkonQgn_prop_nrtyp_phone_mask,
	EMbmAvkonQgn_prop_nrtyp_url,
	EMbmAvkonQgn_prop_nrtyp_url_mask,
	EMbmAvkonQgn_prop_nrtyp_work,
	EMbmAvkonQgn_prop_nrtyp_work_mask,
	EMbmAvkonQgn_note_alarm_calendar,
	EMbmAvkonQgn_note_alarm_calendar_mask,
	EMbmAvkonQgn_note_alarm_clock,
	EMbmAvkonQgn_note_alarm_clock_mask,
	EMbmAvkonQgn_note_alarm_misc,
	EMbmAvkonQgn_note_alarm_misc_mask,
	EMbmAvkonQgn_note_batt_charging,
	EMbmAvkonQgn_note_batt_charging_mask,
	EMbmAvkonQgn_note_batt_full,
	EMbmAvkonQgn_note_batt_full_mask,
	EMbmAvkonQgn_note_batt_low,
	EMbmAvkonQgn_note_batt_low_mask,
	EMbmAvkonQgn_note_batt_not_charging,
	EMbmAvkonQgn_note_batt_not_charging_mask,
	EMbmAvkonQgn_note_batt_recharge,
	EMbmAvkonQgn_note_batt_recharge_mask,
	EMbmAvkonQgn_note_bt,
	EMbmAvkonQgn_note_bt_mask,
	EMbmAvkonQgn_note_call,
	EMbmAvkonQgn_note_call_mask,
	EMbmAvkonQgn_note_copy,
	EMbmAvkonQgn_note_copy_mask,
	EMbmAvkonQgn_note_erased,
	EMbmAvkonQgn_note_erased_mask,
	EMbmAvkonQgn_note_error,
	EMbmAvkonQgn_note_error_mask,
	EMbmAvkonQgn_note_info,
	EMbmAvkonQgn_note_info_mask,
	EMbmAvkonQgn_note_mail,
	EMbmAvkonQgn_note_mail_mask,
	EMbmAvkonQgn_note_message,
	EMbmAvkonQgn_note_message_mask,
	EMbmAvkonQgn_note_mms,
	EMbmAvkonQgn_note_mms_mask,
	EMbmAvkonQgn_note_move,
	EMbmAvkonQgn_note_move_mask,
	EMbmAvkonQgn_note_ok,
	EMbmAvkonQgn_note_ok_mask,
	EMbmAvkonQgn_note_progress,
	EMbmAvkonQgn_note_progress_mask,
	EMbmAvkonQgn_note_query,
	EMbmAvkonQgn_note_query_mask,
	EMbmAvkonQgn_note_remote_mailbox,
	EMbmAvkonQgn_note_remote_mailbox_mask,
	EMbmAvkonQgn_note_sml,
	EMbmAvkonQgn_note_sml_mask,
	EMbmAvkonQgn_note_voice,
	EMbmAvkonQgn_note_voice_mask,
	EMbmAvkonQgn_note_voice_found,
	EMbmAvkonQgn_note_voice_found_mask,
	EMbmAvkonQgn_note_warning,
	EMbmAvkonQgn_note_warning_mask,
	EMbmAvkonQgn_note_warr,
	EMbmAvkonQgn_note_warr_mask,
	EMbmAvkonQgn_stat_alarm,
	EMbmAvkonQgn_stat_bt,
	EMbmAvkonQgn_stat_bt_uni,
	EMbmAvkonQgn_stat_bt_blank,
	EMbmAvkonQgn_stat_bt_uni_blank,
	EMbmAvkonQgn_stat_mod_bt,
	EMbmAvkonQgn_stat_divert_vm,
	EMbmAvkonQgn_stat_divert0,
	EMbmAvkonQgn_stat_divert1,
	EMbmAvkonQgn_stat_divert2,
	EMbmAvkonQgn_stat_divert12,
	EMbmAvkonQgn_stat_ir,
	EMbmAvkonQgn_stat_ir_blank,
	EMbmAvkonQgn_stat_ir_uni,
	EMbmAvkonQgn_stat_ir_uni_blank,
	EMbmAvkonQgn_stat_keyguard,
	EMbmAvkonQgn_stat_line2,
	EMbmAvkonQgn_stat_message,
	EMbmAvkonQgn_stat_message_blank,
	EMbmAvkonQgn_stat_message_uni,
	EMbmAvkonQgn_stat_message_uni_blank,
	EMbmAvkonQgn_stat_message_mail,
	EMbmAvkonQgn_stat_message_mail_uni,
	EMbmAvkonQgn_stat_message_data,
	EMbmAvkonQgn_stat_message_data_uni,
	EMbmAvkonQgn_stat_message_fax,
	EMbmAvkonQgn_stat_message_fax_uni,
	EMbmAvkonQgn_stat_cyphering_on,
	EMbmAvkonQgn_stat_cyphering_on_uni,
	EMbmAvkonQgn_stat_zone_home,
	EMbmAvkonQgn_stat_outbox,
	EMbmAvkonQgn_stat_outbox_uni,
	EMbmAvkonQgn_stat_vm0,
	EMbmAvkonQgn_stat_vm0_uni,
	EMbmAvkonQgn_stat_vm1,
	EMbmAvkonQgn_stat_vm1_uni,
	EMbmAvkonQgn_stat_vm2,
	EMbmAvkonQgn_stat_vm2_uni,
	EMbmAvkonQgn_stat_vm12,
	EMbmAvkonQgn_stat_vm12_uni,
	EMbmAvkonQgn_stat_zone_viag,
	EMbmAvkonQgn_stat_headset,
	EMbmAvkonQgn_stat_loopset,
	EMbmAvkonQgn_stat_ihf_uni,
	EMbmAvkonQgn_indi_scroll_a,
	EMbmAvkonQgn_indi_scroll_b,
	EMbmAvkonQgn_note_empty,
	EMbmAvkonQgn_note_empty_mask,
	EMbmAvkonQgn_menu_unknown_cxt,
	EMbmAvkonQgn_menu_unknown_cxt_mask,
	EMbmAvkonQgn_menu_unknown_lst,
	EMbmAvkonQgn_menu_unknown_lst_mask,
	EMbmAvkonQgn_prop_bt_carkit,
	EMbmAvkonQgn_prop_bt_carkit_mask,
	EMbmAvkonQgn_prop_bt_computer,
	EMbmAvkonQgn_prop_bt_computer_mask,
	EMbmAvkonQgn_prop_bt_headset,
	EMbmAvkonQgn_prop_bt_headset_mask,
	EMbmAvkonQgn_prop_bt_misc,
	EMbmAvkonQgn_prop_bt_misc_mask,
	EMbmAvkonQgn_prop_bt_phone,
	EMbmAvkonQgn_prop_bt_phone_mask,
	EMbmAvkonQgn_prop_bt_unknown,
	EMbmAvkonQgn_prop_bt_unknown_mask,
	EMbmAvkonQgn_note_batt_charging_2,
	EMbmAvkonQgn_note_batt_charging_2_mask,
	EMbmAvkonQgn_note_batt_charging_3,
	EMbmAvkonQgn_note_batt_charging_3_mask,
	EMbmAvkonQgn_note_batt_charging_4,
	EMbmAvkonQgn_note_batt_charging_4_mask,
	EMbmAvkonQgn_note_batt_charging_5,
	EMbmAvkonQgn_note_batt_charging_5_mask,
	EMbmAvkonQgn_note_batt_full_2,
	EMbmAvkonQgn_note_batt_full_2_mask,
	EMbmAvkonQgn_note_batt_low_2,
	EMbmAvkonQgn_note_batt_low_2_mask,
	EMbmAvkonQgn_note_batt_not_charging_2,
	EMbmAvkonQgn_note_batt_not_charging_2_mask,
	EMbmAvkonQgn_note_batt_not_charging_3,
	EMbmAvkonQgn_note_batt_not_charging_3_mask,
	EMbmAvkonQgn_note_batt_recharge_2,
	EMbmAvkonQgn_note_batt_recharge_2_mask,
	EMbmAvkonQgn_note_batt_recharge_3,
	EMbmAvkonQgn_note_batt_recharge_3_mask,
	EMbmAvkonQgn_note_batt_recharge_4,
	EMbmAvkonQgn_note_batt_recharge_4_mask,
	EMbmAvkonQgn_note_query_2,
	EMbmAvkonQgn_note_query_2_mask,
	EMbmAvkonQgn_note_query_3,
	EMbmAvkonQgn_note_query_3_mask,
	EMbmAvkonQgn_note_query_4,
	EMbmAvkonQgn_note_query_4_mask,
	EMbmAvkonQgn_note_query_5,
	EMbmAvkonQgn_note_query_5_mask,
	EMbmAvkonQgn_note_ok_2,
	EMbmAvkonQgn_note_ok_2_mask,
	EMbmAvkonQgn_note_ok_3,
	EMbmAvkonQgn_note_ok_3_mask,
	EMbmAvkonQgn_note_ok_4,
	EMbmAvkonQgn_note_ok_4_mask,
	EMbmAvkonQgn_note_ok_5,
	EMbmAvkonQgn_note_ok_5_mask,
	EMbmAvkonQgn_note_erased_2,
	EMbmAvkonQgn_note_erased_2_mask,
	EMbmAvkonQgn_note_erased_3,
	EMbmAvkonQgn_note_erased_3_mask,
	EMbmAvkonQgn_note_erased_4,
	EMbmAvkonQgn_note_erased_4_mask,
	EMbmAvkonQgn_note_erased_5,
	EMbmAvkonQgn_note_erased_5_mask,
	EMbmAvkonQgn_note_erased_6,
	EMbmAvkonQgn_note_erased_6_mask,
	EMbmAvkonQgn_note_erased_7,
	EMbmAvkonQgn_note_erased_7_mask,
	EMbmAvkonQgn_note_erased_8,
	EMbmAvkonQgn_note_erased_8_mask,
	EMbmAvkonQgn_note_info_2,
	EMbmAvkonQgn_note_info_2_mask,
	EMbmAvkonQgn_note_info_3,
	EMbmAvkonQgn_note_info_3_mask,
	EMbmAvkonQgn_note_info_4,
	EMbmAvkonQgn_note_info_4_mask,
	EMbmAvkonQgn_note_info_5,
	EMbmAvkonQgn_note_info_5_mask,
	EMbmAvkonQgn_note_warning_2,
	EMbmAvkonQgn_note_warning_2_mask,
	EMbmAvkonQgn_note_error_2,
	EMbmAvkonQgn_note_error_2_mask,
	EMbmAvkonQgn_graf_progress_bar,
	EMbmAvkonQgn_graf_progress_bar_mask,
	EMbmAvkonQgn_graf_vorec_progress_bar,
	EMbmAvkonQgn_graf_vorec_progress_bar_mask,
	EMbmAvkonQgn_graf_vorec_bar_background,
	EMbmAvkonQgn_graf_vorec_bar_background_mask,
	EMbmAvkonQgn_graf_wait_bar_background,
	EMbmAvkonQgn_graf_wait_bar_background_mask,
	EMbmAvkonQgn_graf_wait_bar_1,
	EMbmAvkonQgn_graf_wait_bar_1_mask,
	EMbmAvkonQgn_graf_wait_bar_2,
	EMbmAvkonQgn_graf_wait_bar_2_mask,
	EMbmAvkonQgn_graf_wait_bar_3,
	EMbmAvkonQgn_graf_wait_bar_3_mask,
	EMbmAvkonQgn_graf_wait_bar_4,
	EMbmAvkonQgn_graf_wait_bar_4_mask,
	EMbmAvkonQgn_graf_wait_bar_5,
	EMbmAvkonQgn_graf_wait_bar_5_mask,
	EMbmAvkonQgn_graf_wait_bar_6,
	EMbmAvkonQgn_graf_wait_bar_6_mask,
	EMbmAvkonQgn_graf_wait_bar_7,
	EMbmAvkonQgn_graf_wait_bar_7_mask,
	EMbmAvkonQgn_graf_navi_wipe_blue,
	EMbmAvkonQgn_graf_navi_wipe_green,
	EMbmAvkonQgn_graf_navi_wipe_purple,
	EMbmAvkonQgn_note_keyguard,
	EMbmAvkonQgn_note_keyguard_mask,
	EMbmAvkonQgn_note_keyguard_2,
	EMbmAvkonQgn_note_keyguard_2_mask,
	EMbmAvkonQgn_note_keyguard_3,
	EMbmAvkonQgn_note_keyguard_3_mask,
	EMbmAvkonQgn_note_keyguard_4,
	EMbmAvkonQgn_note_keyguard_4_mask,
	EMbmAvkonQgn_note_keyguard_5,
	EMbmAvkonQgn_note_keyguard_5_mask,
	EMbmAvkonQgn_note_keyguard_6,
	EMbmAvkonQgn_note_keyguard_6_mask,
	EMbmAvkonQgn_note_keyguard_7,
	EMbmAvkonQgn_note_keyguard_7_mask,
	EMbmAvkonQgn_note_keyguard_8,
	EMbmAvkonQgn_note_keyguard_8_mask,
	EMbmAvkonQgn_stat_chi_pinyin,
	EMbmAvkonQgn_stat_chi_pinyin_mask,
	EMbmAvkonQgn_stat_chi_pinyin_query,
	EMbmAvkonQgn_stat_chi_pinyin_query_mask,
	EMbmAvkonQgn_stat_chi_stroke,
	EMbmAvkonQgn_stat_chi_stroke_mask,
	EMbmAvkonQgn_stat_chi_stroke_query,
	EMbmAvkonQgn_stat_chi_stroke_query_mask,
	EMbmAvkonQgn_stat_chi_zhuyin,
	EMbmAvkonQgn_stat_chi_zhuyin_mask,
	EMbmAvkonQgn_stat_chi_zhuyin_query,
	EMbmAvkonQgn_stat_chi_zhuyin_query_mask,
	EMbmAvkonQgn_indi_missed_call_one,
	EMbmAvkonQgn_indi_missed_call_two,
	EMbmAvkonQgn_indi_missed_mess_one,
	EMbmAvkonQgn_indi_missed_mess_two,
	EMbmAvkonQgn_graf_contrast,
	EMbmAvkonQgn_graf_splash_screen,
	EMbmAvkonLshellicon,
	EMbmAvkonLshelliconm,
	EMbmAvkonQgn_indi_speaker,
	EMbmAvkonQgn_indi_speaker_mask,
	EMbmAvkonQgn_indi_earpiece,
	EMbmAvkonQgn_indi_earpiece_mask,
	EMbmAvkonQgn_menu_smsvo_cxt,
	EMbmAvkonQgn_menu_smsvo_cxt_mask,
	EMbmAvkonQgn_stat_chi_zhuyin_find,
	EMbmAvkonQgn_stat_chi_zhuyin_find_mask,
	EMbmAvkonQgn_stat_chi_zhuyin_find_query,
	EMbmAvkonQgn_stat_chi_zhuyin_find_query_mask,
	EMbmAvkonQgn_stat_chi_stroke_find,
	EMbmAvkonQgn_stat_chi_stroke_find_mask,
	EMbmAvkonQgn_stat_chi_stroke_find_query,
	EMbmAvkonQgn_stat_chi_stroke_find_query_mask,
	EMbmAvkonQgn_indi_chi_find_small,
	EMbmAvkonQgn_indi_chi_find_numeric,
	EMbmAvkonQgn_indi_chi_find_pinyin,
	EMbmAvkonQgn_indi_chi_find_zhuyin,
	EMbmAvkonQgn_indi_chi_find_zhuyin_symbol,
	EMbmAvkonQgn_indi_chi_find_stroke_simple,
	EMbmAvkonQgn_indi_chi_find_stroke_trad,
	EMbmAvkonQgn_indi_chi_find_stroke_symbol,
	EMbmAvkonQgn_stat_chi_stroke_trad,
	EMbmAvkonQgn_stat_chi_stroke_trad_mask,
	EMbmAvkonQgn_stat_chi_stroke_trad_query,
	EMbmAvkonQgn_stat_chi_stroke_trad_query_mask,
	EMbmAvkonQgn_stat_im_uni,
	EMbmAvkonQgn_prop_empty,
	EMbmAvkonQgn_prop_empty_mask,
	EMbmAvkonQgn_bt_connect_on,
	EMbmAvkonQgn_bt_connect_on_mask,
	EMbmAvkonQgn_stat_tty,
	EMbmAvkonQgn_prop_bt_audio,
	EMbmAvkonQgn_prop_bt_audio_mask,
	EMbmAvkonQgn_prop_file_small,
	EMbmAvkonQgn_prop_file_small_mask,
	EMbmAvkonQgn_prop_phone_memc,
	EMbmAvkonQgn_prop_phone_memc_mask,
	EMbmAvkonQgn_indi_no_signal,
	EMbmAvkonQgn_indi_no_signal_mask,
	EMbmAvkonQgn_stat_usb,
	EMbmAvkonQgn_stat_usb_uni,
	EMbmAvkonQgn_stat_missed_calls_uni,
	EMbmAvkonQgn_stat_case_arabic,
	EMbmAvkonQgn_stat_case_arabic_mask,
	EMbmAvkonQgn_stat_case_arabic_query,
	EMbmAvkonQgn_stat_case_arabic_query_mask,
	EMbmAvkonQgn_stat_case_hebrew,
	EMbmAvkonQgn_stat_case_hebrew_mask,
	EMbmAvkonQgn_stat_case_hebrew_query,
	EMbmAvkonQgn_stat_case_hebrew_query_mask,
	EMbmAvkonQgn_stat_case_arabic_numeric,
	EMbmAvkonQgn_stat_case_arabic_numeric_mask,
	EMbmAvkonQgn_stat_case_arabic_numeric_query,
	EMbmAvkonQgn_stat_case_arabic_numeric_query_mask,
	EMbmAvkonQgn_stat_message_ps,
	EMbmAvkonQgn_stat_missed_call_ps,
	EMbmAvkonQgn_indi_submenu,
	EMbmAvkonQgn_indi_submenu_mask,
	EMbmAvkonQgn_graf_fswap_ext,
	EMbmAvkonQgn_graf_fswap_ext_mask,
	EMbmAvkonQgn_graf_snot_add_1,
	EMbmAvkonQgn_graf_snot_add_1_mask,
	EMbmAvkonQgn_graf_snot_add_2,
	EMbmAvkonQgn_graf_snot_add_2_mask,
	EMbmAvkonQgn_indi_signal_gprs_multipdp,
	EMbmAvkonQgn_indi_signal_gprs_multipdp_mask,
	EMbmAvkonQgn_prop_phone_memc_large,
	EMbmAvkonQgn_prop_phone_memc_large_mask,
	EMbmAvkonQgn_prop_mmc_memc_large,
	EMbmAvkonQgn_prop_mmc_memc_large_mask,
	EMbmAvkonQgn_indi_dst_add,
	EMbmAvkonQgn_indi_dst_add_mask,
	EMbmAvkonQgn_stat_message_remote,
	EMbmAvkonQgn_stat_message_remote_uni,
	EMbmAvkonQgn_stat_message_other,
	EMbmAvkonQgn_stat_message_other_uni,
	EMbmAvkonQgn_graf_navi_wipe_grey,
	EMbmAvkonQgn_graf_navi_wipe_1,
	EMbmAvkonQgn_graf_navi_wipe_2,
	EMbmAvkonQgn_graf_navi_wipe_3,
	EMbmAvkonQgn_graf_navi_wipe_4,
	EMbmAvkonQgn_graf_navi_wipe_5,
	EMbmAvkonQgn_graf_navi_wipe_6,
	EMbmAvkonQgn_graf_navi_wipe_7,
	EMbmAvkonQgn_graf_navi_wipe_8,
	EMbmAvkonQgn_graf_navi_wipe_9,
	EMbmAvkonQgn_graf_navi_wipe_10,
	EMbmAvkonQgn_graf_navi_wipe_11,
	EMbmAvkonQgn_graf_navi_wipe_12,
	EMbmAvkonQgn_graf_navi_wipe_13,
	EMbmAvkonQgn_stat_loc,
	EMbmAvkonQgn_prop_folder_sub_small,
	EMbmAvkonQgn_prop_folder_sub_small_mask,
	EMbmAvkonQgn_prop_folder_current,
	EMbmAvkonQgn_prop_folder_current_mask,
	EMbmAvkonQgn_graf_status_small_prog,
	EMbmAvkonQgn_graf_status_small_prog_mask,
	EMbmAvkonQgn_graf_status_small_wait_01,
	EMbmAvkonQgn_graf_status_small_wait_01_mask,
	EMbmAvkonQgn_graf_status_small_wait_02,
	EMbmAvkonQgn_graf_status_small_wait_02_mask,
	EMbmAvkonQgn_graf_status_small_wait_03,
	EMbmAvkonQgn_graf_status_small_wait_03_mask,
	EMbmAvkonQgn_graf_status_small_wait_04,
	EMbmAvkonQgn_graf_status_small_wait_04_mask,
	EMbmAvkonQgn_graf_status_small_wait_05,
	EMbmAvkonQgn_graf_status_small_wait_05_mask,
	EMbmAvkonQgn_graf_status_small_wait_06,
	EMbmAvkonQgn_graf_status_small_wait_06_mask,
	EMbmAvkonQgn_graf_status_small_wait_07,
	EMbmAvkonQgn_graf_status_small_wait_07_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_01,
	EMbmAvkonQgn_graf_wml_wait_globe_01_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_02,
	EMbmAvkonQgn_graf_wml_wait_globe_02_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_03,
	EMbmAvkonQgn_graf_wml_wait_globe_03_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_04,
	EMbmAvkonQgn_graf_wml_wait_globe_04_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_05,
	EMbmAvkonQgn_graf_wml_wait_globe_05_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_06,
	EMbmAvkonQgn_graf_wml_wait_globe_06_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_07,
	EMbmAvkonQgn_graf_wml_wait_globe_07_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_08,
	EMbmAvkonQgn_graf_wml_wait_globe_08_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_09,
	EMbmAvkonQgn_graf_wml_wait_globe_09_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_10,
	EMbmAvkonQgn_graf_wml_wait_globe_10_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_11,
	EMbmAvkonQgn_graf_wml_wait_globe_11_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_12,
	EMbmAvkonQgn_graf_wml_wait_globe_12_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_13,
	EMbmAvkonQgn_graf_wml_wait_globe_13_mask,
	EMbmAvkonQgn_graf_wml_wait_globe_14,
	EMbmAvkonQgn_graf_wml_wait_globe_14_mask,
	EMbmAvkonQgn_indi_cursor_lr,
	EMbmAvkonQgn_indi_cursor_rl,
	EMbmAvkonQgn_indi_cursor_lr_12,
	EMbmAvkonQgn_indi_cursor_rl_12,
	EMbmAvkonQgn_stat_ihf,
	EMbmAvkonQgn_indi_find_goto,
	EMbmAvkonQgn_indi_find_goto_mask,
	EMbmAvkonQgn_note_im_message,
	EMbmAvkonQgn_note_im_message_mask,
	EMbmAvkonQgn_prop_folder_apps_medium,
	EMbmAvkonQgn_prop_folder_apps_medium_mask,
	EMbmAvkonQgn_stat_headset_unavailable,
	EMbmAvkonQgn_stat_case_thai,
	EMbmAvkonQgn_stat_case_thai_mask,
	EMbmAvkonQgn_indi_earpiece_muted,
	EMbmAvkonQgn_indi_cam_zoom_2_video,
	EMbmAvkonQgn_indi_signal_pd_attach,
	EMbmAvkonQgn_indi_signal_pd_context,
	EMbmAvkonQgn_indi_signal_pd_multipdp,
	EMbmAvkonQgn_indi_signal_pd_suspended,
	EMbmAvkonQgn_indi_signal_wcdma_icon,
	EMbmAvkonQgn_indi_signal_wcdma_attach,
	EMbmAvkonQgn_indi_signal_wcdma_context,
	EMbmAvkonQgn_indi_signal_wcdma_multipdp,
	EMbmAvkonQgn_stat_case_capital_full,
	EMbmAvkonQgn_stat_case_numeric_full,
	EMbmAvkonQgn_stat_case_small_full,
	EMbmAvkonQgn_stat_case_text_full,
	EMbmAvkonQgn_stat_japin_hiragana,
	EMbmAvkonQgn_stat_japin_hiragana_only,
	EMbmAvkonQgn_stat_japin_katakana_full,
	EMbmAvkonQgn_stat_japin_katakana_half,
	EMbmAvkonQgn_stat_loc_off,
	EMbmAvkonQgn_stat_loc_on,
	EMbmAvkonQgn_stat_cdma_roaming,
	EMbmAvkonQgn_prop_nrtyp_video,
	EMbmAvkonQgn_prop_nrtyp_video_mask,
	EMbmAvkonQgn_stat_cdma_roaming_uni,
	EMbmAvkonQgn_graf_navi_wipe_blue_mask,
	EMbmAvkonQgn_stat_case_shift,
	EMbmAvkonQgn_indi_jap_find_hiragana,
	EMbmAvkonQgn_indi_jap_find_hiragana_only,
	EMbmAvkonQgn_indi_jap_find_katakana_full,
	EMbmAvkonQgn_indi_jap_find_katakana_half,
	EMbmAvkonQgn_indi_jap_find_predictive,
	EMbmAvkonQgn_indi_jap_find_case_small_full,
	EMbmAvkonQgn_indi_jap_find_case_numeric_full,
	EMbmAvkonQgn_indi_thai_find_small,
	EMbmAvkonQgn_graf_bar_wait_1,
	EMbmAvkonQgn_graf_bar_wait_2,
	EMbmAvkonQgn_graf_bar_wait_3,
	EMbmAvkonQgn_graf_bar_wait_4,
	EMbmAvkonQgn_graf_bar_wait_5,
	EMbmAvkonQgn_graf_bar_wait_6,
	EMbmAvkonQgn_graf_bar_wait_7,
	EMbmAvkonQgn_graf_bar_wait_idle,
	EMbmAvkonQgn_graf_bar_wait_increm,
	EMbmAvkonQgn_graf_bar_wait_increm_02,
	EMbmAvkonQgn_graf_bar_wait_increm_03,
	EMbmAvkonQgn_graf_bar_wait_increm_04,
	EMbmAvkonQgn_graf_bar_wait_increm_05,
	EMbmAvkonQgn_graf_bar_wait_increm_06,
	EMbmAvkonQgn_graf_bar_wait_increm_07,
	EMbmAvkonQgn_graf_bar_wait_increm_08,
	EMbmAvkonQgn_graf_bar_wait_increm_09,
	EMbmAvkonQgn_graf_bar_wait_increm_10,
	EMbmAvkonQgn_graf_bar_wait_increm_11,
	EMbmAvkonQgn_graf_bar_wait_increm_12,
	EMbmAvkonQgn_graf_bar_wait_increm_13,
	EMbmAvkonQgn_graf_bar_wait_increm_14,
	EMbmAvkonQgn_graf_bar_wait_increm_15,
	EMbmAvkonQgn_graf_bar_wait_increm_16,
	EMbmAvkonQgn_graf_bar_wait_increm_17,
	EMbmAvkonQgn_graf_bar_wait_increm_18,
	EMbmAvkonQgn_graf_bar_wait_increm_19,
	EMbmAvkonQgn_graf_bar_wait_increm_idle,
	EMbmAvkonQgn_graf_bar_progress,
	EMbmAvkonQgn_graf_bar_frame_long,
	EMbmAvkonQgn_graf_bar_frame_long_mask,
	EMbmAvkonQgn_indi_speaker_muted,
	EMbmAvkonQgn_indi_speaker_muted_mask,
	EMbmAvkonQgn_indi_signal_receiving_cdma_01,
	EMbmAvkonQgn_indi_signal_receiving_cdma_02,
	EMbmAvkonQgn_indi_signal_receiving_cdma_03,
	EMbmAvkonQgn_indi_signal_receiving_cdma_04,
	EMbmAvkonQgn_indi_signal_receiving_cdma_05,
	EMbmAvkonQgn_indi_signal_receiving_cdma_06,
	EMbmAvkonQgn_indi_signal_receiving_cdma_07,
	EMbmAvkonQgn_indi_signal_receiving_cdma_08,
	EMbmAvkonQgn_indi_signal_receiving_cdma_09,
	EMbmAvkonQgn_indi_signal_receiving_cdma_10,
	EMbmAvkonQgn_indi_signal_receiving_cdma_11,
	EMbmAvkonQgn_indi_signal_receiving_cdma_12,
	EMbmAvkonQgn_indi_signal_receiving_cdma_13,
	EMbmAvkonQgn_indi_signal_receiving_cdma_14,
	EMbmAvkonQgn_indi_signal_sending_cdma_01,
	EMbmAvkonQgn_indi_signal_sending_cdma_02,
	EMbmAvkonQgn_indi_signal_sending_cdma_03,
	EMbmAvkonQgn_indi_signal_sending_cdma_04,
	EMbmAvkonQgn_indi_signal_sending_cdma_05,
	EMbmAvkonQgn_indi_signal_sending_cdma_06,
	EMbmAvkonQgn_indi_signal_sending_cdma_07,
	EMbmAvkonQgn_indi_signal_sending_cdma_08,
	EMbmAvkonQgn_indi_signal_sending_cdma_09,
	EMbmAvkonQgn_indi_signal_sending_cdma_10,
	EMbmAvkonQgn_indi_signal_sending_cdma_11,
	EMbmAvkonQgn_indi_signal_sending_cdma_12,
	EMbmAvkonQgn_indi_signal_sending_cdma_13,
	EMbmAvkonQgn_indi_signal_sending_cdma_14,
	EMbmAvkonQgn_indi_signal_active_cdma,
	EMbmAvkonQgn_indi_signal_dormant_cdma,
	EMbmAvkonQgn_indi_signal_not_avail_cdma,
	EMbmAvkonQgn_indi_signal_no_service,
	EMbmAvkonQgn_graf_bar_frame_short,
	EMbmAvkonQgn_graf_bar_frame_short_mask,
	EMbmAvkonQgn_graf_bar_frame_vorec,
	EMbmAvkonQgn_graf_bar_frame_vorec_mask,
	EMbmAvkonQgn_graf_bar_progress_mask,
	EMbmAvkonQgn_graf_bar_wait_1_mask,
	EMbmAvkonQgn_graf_bar_wait_2_mask,
	EMbmAvkonQgn_graf_bar_wait_3_mask,
	EMbmAvkonQgn_graf_bar_wait_4_mask,
	EMbmAvkonQgn_graf_bar_wait_5_mask,
	EMbmAvkonQgn_graf_bar_wait_6_mask,
	EMbmAvkonQgn_graf_bar_wait_7_mask,
	EMbmAvkonQgn_indi_signal_wcdma_suspended
	};
# 21 "C:\\KG\\LESSA\\Symbian\\data\\LESSA.rss" 2





//  RESOURCE DEFINITIONS 

RESOURCE RSS_SIGNATURE { }

RESOURCE TBUF { buf = "LESSA"; }

RESOURCE EIK_APP_INFO
    {
    status_pane = r_lessa_status_pane;
    }

//----------------------------------------------------
//   
//    r_lessa_hotkeys
//
//----------------------------------------------------
//
RESOURCE HOTKEYS r_lessa_hotkeys
    {
    control =
        {
        HOTKEY { command = EAknCmdExit; key = 'e'; }
        };
    }

//----------------------------------------------------
//   
//    r_lessa_view1
//
//----------------------------------------------------
//
RESOURCE AVKON_VIEW r_lessa_view1
    {
    hotkeys = r_lessa_hotkeys;
    menubar = r_lessa_menubar_view1;  
    cba     = 0x8cc0017  ;    
    }

//----------------------------------------------------
//   
//    r_lessa_menubar_view1
//
//----------------------------------------------------
//
RESOURCE MENU_BAR r_lessa_menubar_view1
    {
    titles =
        {
        MENU_TITLE { menu_pane = r_lessa_app_menu; txt = "App"; },
        MENU_TITLE { menu_pane = r_lessa_view1_menu; txt = "View"; }
        };
    }

//----------------------------------------------------
//   
//    r_lessa_view1_menu
//
//----------------------------------------------------
//
RESOURCE MENU_PANE r_lessa_view1_menu
    {
    items =
        {
        MENU_ITEM { command = ELESSACmdAppTest; txt = "<View1 menu item>" ; }
        };
    }

//----------------------------------------------------
//   
//    r_lessa_view2
//
//----------------------------------------------------
//
RESOURCE AVKON_VIEW r_lessa_view2
    {
    hotkeys = r_lessa_hotkeys;
    menubar = r_lessa_menubar_view2;  
    cba     = 0x8cc0017  ; 
    }

//----------------------------------------------------
//   
//    r_lessa_menubar_view2
//
//----------------------------------------------------
//
RESOURCE MENU_BAR r_lessa_menubar_view2
    {
    titles =
        {
        MENU_TITLE { menu_pane = r_lessa_app_menu; txt = "App"; },
        MENU_TITLE { menu_pane = r_lessa_view2_menu; txt = "View"; }
        };
    }

//----------------------------------------------------
//   
//    r_lessa_view2_menu
//
//----------------------------------------------------
//
RESOURCE MENU_PANE r_lessa_view2_menu
    {
    items =
        {
        MENU_ITEM { command = ELESSACmdAppTest; txt = "<View2 menu item>" ; }
        };
    }

//----------------------------------------------------
//   
//    r_lessa_app_menu
//
//----------------------------------------------------
//
RESOURCE MENU_PANE r_lessa_app_menu
    {
    items =
        {
        MENU_ITEM { command = ELESSACmdAppTest; txt = "<Application menu item>" ; },
        MENU_ITEM { command = EAknCmdExit; txt = "Exit" ; }
        };
    }

RESOURCE STATUS_PANE_APP_MODEL r_lessa_status_pane
    {
	panes =
		{
		SPANE_PANE
			{
			id = 0x100059BD ;
			type = EAknCtNaviPane;
			resource = r_lessa_navi_decorator;
			}
		};
    }

//----------------------------------------------------
//   
//    r_lessa_navi_decorator
//
//----------------------------------------------------
//
RESOURCE NAVI_DECORATOR r_lessa_navi_decorator
    {
    type = ENaviDecoratorControlTabGroup;
    control = TAB_GROUP
		{
		tab_width = EAknTabWidthWithTwoTabs;  // two tabs
		active = 0;
		tabs = {
			TAB
				{
                id = ELESSAView1Tab; // from application hrh
                txt = "View1" ;
                },
			TAB
				{
                id = ELESSAView2Tab;
                txt = "View2" ;
				}
			};
		};
	}


